DROP TABLE IF EXISTS `ocp_digestives_consumed`;

CREATE TABLE `ocp_digestives_consumed` (
  `c_member_id` int(11) NOT NULL,
  `c_frequency` int(11) NOT NULL,
  `c_time` int(10) unsigned NOT NULL,
  PRIMARY KEY (`c_member_id`,`c_frequency`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_digestives_tin`;

CREATE TABLE `ocp_digestives_tin` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `d_subject` longtext NOT NULL,
  `d_message` longtext NOT NULL,
  `d_from_member_id` int(11) DEFAULT NULL,
  `d_to_member_id` int(11) NOT NULL,
  `d_priority` tinyint(4) NOT NULL,
  `d_no_cc` tinyint(1) NOT NULL,
  `d_date_and_time` int(10) unsigned NOT NULL,
  `d_notification_code` varchar(80) NOT NULL,
  `d_code_category` varchar(255) NOT NULL,
  `d_frequency` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `d_date_and_time` (`d_date_and_time`),
  KEY `d_frequency` (`d_frequency`),
  KEY `d_to_member_id` (`d_to_member_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_download_categories`;

CREATE TABLE `ocp_download_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category` int(10) unsigned NOT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `add_date` int(10) unsigned NOT NULL,
  `notes` longtext NOT NULL,
  `description` int(10) unsigned NOT NULL,
  `rep_image` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `child_find` (`parent_id`),
  KEY `ftjoin_dccat` (`category`),
  KEY `ftjoin_dcdescrip` (`description`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=2;

insert into `ocp_download_categories` values('1','301',null,'1332090691','','302','');

DROP TABLE IF EXISTS `ocp_download_downloads`;

CREATE TABLE `ocp_download_downloads` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` int(11) NOT NULL,
  `name` int(10) unsigned NOT NULL,
  `url` varchar(255) NOT NULL,
  `description` int(10) unsigned NOT NULL,
  `author` varchar(80) NOT NULL,
  `comments` int(10) unsigned NOT NULL,
  `num_downloads` int(11) NOT NULL,
  `out_mode_id` int(11) DEFAULT NULL,
  `add_date` int(10) unsigned NOT NULL,
  `edit_date` int(10) unsigned DEFAULT NULL,
  `validated` tinyint(1) NOT NULL,
  `default_pic` int(11) NOT NULL,
  `file_size` int(11) DEFAULT NULL,
  `allow_rating` tinyint(1) NOT NULL,
  `allow_comments` tinyint(4) NOT NULL,
  `allow_trackbacks` tinyint(1) NOT NULL,
  `notes` longtext NOT NULL,
  `download_views` int(11) NOT NULL,
  `download_cost` int(11) NOT NULL,
  `download_submitter_gets_points` tinyint(1) NOT NULL,
  `submitter` int(11) NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `rep_image` varchar(255) NOT NULL,
  `download_licence` int(11) DEFAULT NULL,
  `download_data_mash` longtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `download_views` (`download_views`),
  KEY `category_list` (`category_id`),
  KEY `recent_downloads` (`add_date`),
  KEY `top_downloads` (`num_downloads`),
  KEY `downloadauthor` (`author`),
  KEY `dds` (`submitter`),
  KEY `ddl` (`download_licence`),
  KEY `dvalidated` (`validated`),
  KEY `ftjoin_dname` (`name`),
  KEY `ftjoin_ddescrip` (`description`),
  KEY `ftjoin_dcomments` (`comments`),
  FULLTEXT KEY `download_data_mash` (`download_data_mash`),
  FULLTEXT KEY `original_filename` (`original_filename`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_download_licences`;

CREATE TABLE `ocp_download_licences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `l_title` varchar(255) NOT NULL,
  `l_text` longtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_download_logging`;

CREATE TABLE `ocp_download_logging` (
  `id` int(11) NOT NULL,
  `the_user` int(11) NOT NULL,
  `ip` varchar(40) NOT NULL,
  `date_and_time` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`,`the_user`),
  KEY `calculate_bandwidth` (`date_and_time`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_edit_pings`;

CREATE TABLE `ocp_edit_pings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `the_page` varchar(80) NOT NULL,
  `the_type` varchar(80) NOT NULL,
  `the_id` varchar(80) NOT NULL,
  `the_time` int(10) unsigned NOT NULL,
  `the_member` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_categories`;

CREATE TABLE `ocp_f_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `c_title` varchar(255) NOT NULL,
  `c_description` longtext NOT NULL,
  `c_expanded_by_default` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=3;

insert into `ocp_f_categories` values('1','General','','1'),
 ('2','Staff','','1');

DROP TABLE IF EXISTS `ocp_f_custom_fields`;

CREATE TABLE `ocp_f_custom_fields` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cf_locked` tinyint(1) NOT NULL,
  `cf_name` int(10) unsigned NOT NULL,
  `cf_description` int(10) unsigned NOT NULL,
  `cf_default` longtext NOT NULL,
  `cf_public_view` tinyint(1) NOT NULL,
  `cf_owner_view` tinyint(1) NOT NULL,
  `cf_owner_set` tinyint(1) NOT NULL,
  `cf_type` varchar(80) NOT NULL,
  `cf_required` tinyint(1) NOT NULL,
  `cf_show_in_posts` tinyint(1) NOT NULL,
  `cf_show_in_post_previews` tinyint(1) NOT NULL,
  `cf_order` int(11) NOT NULL,
  `cf_only_group` longtext NOT NULL,
  `cf_encrypted` tinyint(1) NOT NULL,
  `cf_show_on_join_form` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=36;

insert into `ocp_f_custom_fields` values('1','0','14','15','','1','1','1','long_trans','0','0','0','0','','0','0'),
 ('2','0','16','17','','1','1','1','short_text','0','0','0','1','','0','0'),
 ('3','0','18','19','','1','1','1','long_trans','0','0','0','2','','0','0'),
 ('4','0','20','21','','1','1','1','long_trans','0','0','0','3','','0','0'),
 ('5','0','22','23','','1','1','1','long_trans','0','0','0','4','','0','0'),
 ('6','0','24','25','','1','1','1','long_trans','0','0','0','5','','0','0'),
 ('7','0','26','27','','1','1','1','short_text','0','0','0','6','','0','0'),
 ('8','0','28','29','','1','1','1','short_text','0','0','0','7','','0','0'),
 ('9','0','30','31','','0','0','0','long_trans','0','0','0','8','','0','0'),
 ('10','1','92','93','','0','0','1','short_text','0','0','0','9','','0','0'),
 ('11','1','284','285','0','0','0','0','integer','0','0','0','10','','0','0'),
 ('12','1','297','298','0','0','0','0','integer','0','0','0','11','','0','0'),
 ('13','1','323','324','AED|AFA|ALL|AMD|ANG|AOK|AON|ARA|ARP|ARS|AUD|AWG|AZM|BAM|BBD|BDT|BGL|BHD|BIF|BMD|BND|BOB|BOP|BRC|BRL|BRR|BSD|BTN|BWP|BYR|BZD|CAD|CDZ|CHF|CLF|CLP|CNY|COP|CRC|CSD|CUP|CVE|CYP|CZK|DJF|DKK|DOP|DZD|EEK|EGP|ERN|ETB|EUR|FJD|FKP|GBP|GEL|GHC|GIP|GMD|GNS|GQE|GTQ|GWP|GYD|HKD|HNL|HRD|HRK|HTG|HUF|IDR|ILS|INR|IQD|IRR|ISK|JMD|JOD|JPY|KES|KGS|KHR|KMF|KPW|KRW|KWD|KYD|KZT|LAK|LBP|LKR|LRD|LSL|LSM|LTL|LVL|LYD|MAD|MDL|MGF|MKD|MLF|MMK|MNT|MOP|MRO|MTL|MUR|MVR|MWK|MXN|MYR|MZM|NAD|NGN|NIC|NOK|NPR|NZD|OMR|PAB|PEI|PEN|PGK|PHP|PKR|PLN|PYG|QAR|ROL|RUB|RWF|SAR|SBD|SCR|SDD|SDP|SEK|SGD|SHP|SIT|SKK|SLL|SOS|SRG|STD|SUR|SVC|SYP|SZL|THB|TJR|TMM|TND|TOP|TPE|TRL|TTD|TWD|TZS|UAH|UAK|UGS|USD|UYU|UZS|VEB|VND|VUV|WST|XAF|XCD|XOF|XPF|YDD|YER|ZAL|ZAR|ZMK|ZWD','0','0','1','list','0','0','0','12','','0','0'),
 ('14','1','325','326','','0','0','1','short_text','0','0','0','13','','1','0'),
 ('15','1','327','328','American Express|Delta|Diners Card|JCB|Master Card|Solo|Switch|Visa','0','0','1','list','0','0','0','14','','1','0'),
 ('16','1','329','330','','0','0','1','integer','0','0','0','15','','1','0'),
 ('17','1','331','332','mm/yy','0','0','1','short_text','0','0','0','16','','1','0'),
 ('18','1','333','334','mm/yy','0','0','1','short_text','0','0','0','17','','1','0'),
 ('19','1','335','336','','0','0','1','short_text','0','0','0','18','','1','0'),
 ('20','1','337','338','','0','0','1','short_text','0','0','0','19','','1','0'),
 ('21','1','351','352','','0','0','0','short_text','0','0','0','20','','0','0'),
 ('22','1','353','354','','0','0','0','short_text','0','0','0','21','','0','0'),
 ('23','1','355','356','','0','0','0','long_text','0','0','0','22','','0','0'),
 ('24','1','357','358','','0','0','0','short_text','0','0','0','23','','0','0'),
 ('25','1','359','360','','0','0','0','short_text','0','0','0','24','','0','0'),
 ('26','1','361','362','','0','0','0','short_text','0','0','0','25','','0','0'),
 ('27','1','363','364','|AD|AE|AF|AG|AI|AL|AM|AN|AO|AQ|AR|AS|AT|AU|AW|AZ|BA|BB|BD|BE|BF|BG|BH|BI|BJ|BM|BN|BO|BR|BS|BT|BU|BV|BW|BY|BZ|CA|CC|CD|CF|CG|CH|CI|CK|CL|CM|CN|CO|CR|CS|CU|CV|CX|CY|CZ|DE|DJ|DK|DM|DO|DZ|EC|EE|EG|EH|ER|ES|ET|FI|FJ|FK|FM|FO|FR|GA|GB|GD|GE|GH|GI|GL|GM|GN|GQ|GR|GS|GT|GU|GW|GY|HK|HM|HN|HR|HT|HU|ID|IE|IL|IN|IO|IQ|IR|IS|IT|JM|JO|JP|KE|KG|KH|KI|KM|KN|KP|KR|KW|KY|KZ|LA|LB|LC|LI|LK|LR|LS|LT|LU|LY|MA|MC|MD|MG|MH|MK|ML|MM|MN|MO|MP|MR|MS|MT|MU|MV|MW|MX|MY|MZ|NA|NC|NE|NF|NG|NI|NL|NO|NP|NR|NU|NZ|OM|PA|PE|PF|PG|PH|PK|PL|PN|PR|PT|PW|PY|QA|RO|RU|RW|SA|SB|SC|SD|SE|SG|SH|SI|SJ|SK|SL|SM|SN|SO|SR|ST|SU|SV|SY|SZ|TC|TD|TG|TH|TJ|TK|TM|TN|TO|TP|TR|TT|TV|TW|TZ|UA|UG|UM|US|UY|UZ|VA|VC|VE|VG|VI|VN|VU|WF|WS|YD|YE|ZA|ZM|ZR|ZW','0','0','0','list','0','0','0','26','','0','0'),
 ('28','1','387','388','0','0','0','0','integer','0','0','0','27','','0','0'),
 ('29','1','389','390','0','0','0','0','integer','0','0','0','28','','0','0'),
 ('30','1','391','392','0','0','0','0','integer','0','0','0','29','','0','0'),
 ('31','1','393','394','0','0','0','0','integer','0','0','0','30','','0','0'),
 ('32','1','395','396','0','0','0','0','integer','0','0','0','31','','0','0'),
 ('33','1','397','398','','0','0','0','short_text','0','0','0','32','','0','0'),
 ('34','1','399','400','','0','0','1','short_text','0','0','0','33','','0','0'),
 ('35','1','401','402','','0','0','1','short_text','0','0','0','34','','0','0');

DROP TABLE IF EXISTS `ocp_f_emoticons`;

CREATE TABLE `ocp_f_emoticons` (
  `e_code` varchar(80) NOT NULL,
  `e_theme_img_code` varchar(255) NOT NULL,
  `e_relevance_level` int(11) NOT NULL,
  `e_use_topics` tinyint(1) NOT NULL,
  `e_is_special` tinyint(1) NOT NULL,
  PRIMARY KEY (`e_code`),
  KEY `relevantemoticons` (`e_relevance_level`),
  KEY `topicemos` (`e_use_topics`)
) ENGINE=MyISAM CHARACTER SET=latin1;

insert into `ocp_f_emoticons` values(':P','ocf_emoticons/cheeky','0','1','0'),
 (':\'(','ocf_emoticons/cry','0','1','0'),
 (':dry:','ocf_emoticons/dry','0','1','0'),
 (':$','ocf_emoticons/blush','0','1','0'),
 (';)','ocf_emoticons/wink','0','0','0'),
 ('O_o','ocf_emoticons/blink','0','1','0'),
 (':wub:','ocf_emoticons/wub','0','1','0'),
 (':cool:','ocf_emoticons/cool','0','1','0'),
 (':lol:','ocf_emoticons/lol','0','1','0'),
 (':(','ocf_emoticons/sad','0','1','0'),
 (':)','ocf_emoticons/smile','0','0','0'),
 (':thumbs:','ocf_emoticons/thumbs','0','1','0'),
 (':offtopic:','ocf_emoticons/offtopic','0','0','0'),
 (':|','ocf_emoticons/mellow','0','0','0'),
 (':ninja:','ocf_emoticons/ph34r','0','1','0'),
 (':o','ocf_emoticons/shocked','0','1','0'),
 (':rolleyes:','ocf_emoticons/rolleyes','1','1','0'),
 (':D','ocf_emoticons/grin','1','1','0'),
 ('^_^','ocf_emoticons/glee','1','1','0'),
 ('(K)','ocf_emoticons/kiss','1','0','0'),
 (':S','ocf_emoticons/confused','1','1','0'),
 (':@','ocf_emoticons/angry','1','1','0'),
 (':shake:','ocf_emoticons/shake','1','1','0'),
 (':hand:','ocf_emoticons/hand','1','1','0'),
 (':drool:','ocf_emoticons/drool','1','1','0'),
 (':devil:','ocf_emoticons/devil','1','1','0'),
 (':party:','ocf_emoticons/party','1','0','0'),
 (':constipated:','ocf_emoticons/constipated','1','1','0'),
 (':depressed:','ocf_emoticons/depressed','1','1','0'),
 (':zzz:','ocf_emoticons/zzz','1','1','0'),
 (':whistle:','ocf_emoticons/whistle','1','0','0'),
 (':upsidedown:','ocf_emoticons/upsidedown','1','1','0'),
 (':sick:','ocf_emoticons/sick','1','1','0'),
 (':shutup:','ocf_emoticons/shutup','1','0','0'),
 (':sarcy:','ocf_emoticons/sarcy','1','1','0'),
 (':puppyeyes:','ocf_emoticons/puppyeyes','1','1','0'),
 (':nod:','ocf_emoticons/nod','1','0','0'),
 (':nerd:','ocf_emoticons/nerd','1','1','0'),
 (':king:','ocf_emoticons/king','1','1','0'),
 (':birthday:','ocf_emoticons/birthday','1','1','0'),
 (':cyborg:','ocf_emoticons/cyborg','1','0','0'),
 (':hippie:','ocf_emoticons/hippie','1','1','0'),
 (':ninja2:','ocf_emoticons/ninja2','1','1','0'),
 (':rockon:','ocf_emoticons/rockon','1','0','0'),
 (':sinner:','ocf_emoticons/sinner','1','0','0'),
 (':guitar:','ocf_emoticons/guitar','1','0','0'),
 (':christmas:','ocf_emoticons/christmas','1','0','0');

DROP TABLE IF EXISTS `ocp_f_forum_intro_ip`;

CREATE TABLE `ocp_f_forum_intro_ip` (
  `i_forum_id` int(11) NOT NULL,
  `i_ip` varchar(40) NOT NULL,
  PRIMARY KEY (`i_forum_id`,`i_ip`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_forum_intro_member`;

CREATE TABLE `ocp_f_forum_intro_member` (
  `i_forum_id` int(11) NOT NULL,
  `i_member_id` int(11) NOT NULL,
  PRIMARY KEY (`i_forum_id`,`i_member_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_forums`;

CREATE TABLE `ocp_f_forums` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `f_name` varchar(255) NOT NULL,
  `f_description` int(10) unsigned NOT NULL,
  `f_category_id` int(11) DEFAULT NULL,
  `f_parent_forum` int(11) DEFAULT NULL,
  `f_position` int(11) NOT NULL,
  `f_order_sub_alpha` tinyint(1) NOT NULL,
  `f_post_count_increment` tinyint(1) NOT NULL,
  `f_intro_question` int(10) unsigned NOT NULL,
  `f_intro_answer` varchar(255) NOT NULL,
  `f_cache_num_topics` int(11) NOT NULL,
  `f_cache_num_posts` int(11) NOT NULL,
  `f_cache_last_topic_id` int(11) DEFAULT NULL,
  `f_cache_last_title` varchar(255) NOT NULL,
  `f_cache_last_time` int(10) unsigned DEFAULT NULL,
  `f_cache_last_username` varchar(255) NOT NULL,
  `f_cache_last_member_id` int(11) DEFAULT NULL,
  `f_cache_last_forum_id` int(11) DEFAULT NULL,
  `f_redirection` varchar(255) NOT NULL,
  `f_order` varchar(80) NOT NULL,
  `f_is_threaded` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `cache_num_posts` (`f_cache_num_posts`),
  KEY `subforum_parenting` (`f_parent_forum`),
  KEY `findnamedforum` (`f_name`),
  KEY `f_position` (`f_position`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=9;

insert into `ocp_f_forums` values('1','Forum home','52',null,null,'1','0','1','53','','0','0',null,'',null,'',null,null,'','last_post','0'),
 ('2','General chat','54','1','1','1','0','1','55','','0','0',null,'',null,'',null,null,'','last_post','0'),
 ('3','Reported posts forum','56','2','1','1','0','1','57','','0','0',null,'',null,'',null,null,'','last_post','0'),
 ('4','Trash','58','2','1','1','0','1','59','','0','0',null,'',null,'',null,null,'','last_post','0'),
 ('5','Website comment topics','60','1','1','1','0','1','61','','0','0',null,'',null,'',null,null,'','last_post','1'),
 ('6','Website support tickets','62','2','1','1','0','1','63','','0','0',null,'',null,'',null,null,'','last_post','0'),
 ('7','Staff','64','2','1','1','0','1','65','','1','1','1','Welcome to the forums','1332090641','System','1','7','','last_post','0'),
 ('8','Website \"Contact Us\" messages','136','2','1','1','0','1','137','','0','0',null,'',null,'',null,null,'','last_post','0');

DROP TABLE IF EXISTS `ocp_f_group_member_timeouts`;

CREATE TABLE `ocp_f_group_member_timeouts` (
  `member_id` int(11) NOT NULL,
  `group_id` int(11) NOT NULL,
  `timeout` int(10) unsigned NOT NULL,
  PRIMARY KEY (`member_id`,`group_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_group_members`;

CREATE TABLE `ocp_f_group_members` (
  `gm_group_id` int(11) NOT NULL,
  `gm_member_id` int(11) NOT NULL,
  `gm_validated` tinyint(1) NOT NULL,
  PRIMARY KEY (`gm_group_id`,`gm_member_id`),
  KEY `gm_validated` (`gm_validated`),
  KEY `gm_member_id` (`gm_member_id`),
  KEY `gm_group_id` (`gm_group_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_groups`;

CREATE TABLE `ocp_f_groups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `g_name` int(10) unsigned NOT NULL,
  `g_is_default` tinyint(1) NOT NULL,
  `g_is_presented_at_install` tinyint(1) NOT NULL,
  `g_is_super_admin` tinyint(1) NOT NULL,
  `g_is_super_moderator` tinyint(1) NOT NULL,
  `g_group_leader` int(11) DEFAULT NULL,
  `g_title` int(10) unsigned NOT NULL,
  `g_promotion_target` int(11) DEFAULT NULL,
  `g_promotion_threshold` int(11) DEFAULT NULL,
  `g_flood_control_submit_secs` int(11) NOT NULL,
  `g_flood_control_access_secs` int(11) NOT NULL,
  `g_gift_points_base` int(11) NOT NULL,
  `g_gift_points_per_day` int(11) NOT NULL,
  `g_max_daily_upload_mb` int(11) NOT NULL,
  `g_max_attachments_per_post` int(11) NOT NULL,
  `g_max_avatar_width` int(11) NOT NULL,
  `g_max_avatar_height` int(11) NOT NULL,
  `g_max_post_length_comcode` int(11) NOT NULL,
  `g_max_sig_length_comcode` int(11) NOT NULL,
  `g_enquire_on_new_ips` tinyint(1) NOT NULL,
  `g_rank_image` varchar(80) NOT NULL,
  `g_hidden` tinyint(1) NOT NULL,
  `g_order` int(11) NOT NULL,
  `g_rank_image_pri_only` tinyint(1) NOT NULL,
  `g_open_membership` tinyint(1) NOT NULL,
  `g_is_private_club` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ftjoin_gname` (`g_name`),
  KEY `ftjoin_gtitle` (`g_title`),
  KEY `is_private_club` (`g_is_private_club`),
  KEY `is_super_admin` (`g_is_super_admin`),
  KEY `is_super_moderator` (`g_is_super_moderator`),
  KEY `is_default` (`g_is_default`),
  KEY `hidden` (`g_hidden`),
  KEY `is_presented_at_install` (`g_is_presented_at_install`),
  KEY `gorder` (`g_order`,`id`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=11;

insert into `ocp_f_groups` values('1','32','0','0','0','0',null,'33',null,null,'5','0','25','1','70','50','100','100','30000','700','0','','0','0','1','0','0'),
 ('2','34','0','0','1','0',null,'35',null,null,'0','0','25','1','70','50','100','100','30000','700','0','ocf_rank_images/admin','0','1','1','0','0'),
 ('3','36','0','0','0','1',null,'37',null,null,'0','0','25','1','70','50','100','100','30000','700','0','ocf_rank_images/mod','0','2','1','0','0'),
 ('4','38','0','0','0','0',null,'39',null,null,'0','0','25','1','70','50','100','100','30000','700','0','','0','3','1','0','0'),
 ('5','40','0','0','0','0',null,'41',null,null,'5','0','25','1','70','50','100','100','30000','700','0','ocf_rank_images/4','0','4','1','0','0'),
 ('6','42','0','0','0','0',null,'43','5','10000','5','0','25','1','70','50','100','100','30000','700','0','ocf_rank_images/3','0','5','1','0','0'),
 ('7','44','0','0','0','0',null,'45','6','2500','5','0','25','1','70','50','100','100','30000','700','0','ocf_rank_images/2','0','6','1','0','0'),
 ('8','46','0','0','0','0',null,'47','7','400','5','0','25','1','70','50','100','100','30000','700','0','ocf_rank_images/1','0','7','1','0','0'),
 ('9','48','0','0','0','0',null,'49','8','100','5','0','25','1','70','50','100','100','30000','700','0','ocf_rank_images/0','0','8','1','0','0'),
 ('10','50','0','0','0','0',null,'51',null,null,'0','0','25','1','70','50','100','100','30000','700','0','','0','9','1','0','0');

DROP TABLE IF EXISTS `ocp_f_invites`;

CREATE TABLE `ocp_f_invites` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `i_inviter` int(11) NOT NULL,
  `i_email_address` varchar(255) NOT NULL,
  `i_time` int(10) unsigned NOT NULL,
  `i_taken` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_member_cpf_perms`;

CREATE TABLE `ocp_f_member_cpf_perms` (
  `member_id` int(11) NOT NULL,
  `field_id` int(11) NOT NULL,
  `guest_view` tinyint(1) NOT NULL,
  `member_view` tinyint(1) NOT NULL,
  `friend_view` tinyint(1) NOT NULL,
  `group_view` varchar(255) NOT NULL,
  PRIMARY KEY (`member_id`,`field_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_member_custom_fields`;

CREATE TABLE `ocp_f_member_custom_fields` (
  `mf_member_id` int(11) NOT NULL,
  `field_1` int(10) unsigned NOT NULL DEFAULT '0',
  `field_2` varchar(255) NOT NULL DEFAULT '',
  `field_3` int(10) unsigned NOT NULL DEFAULT '0',
  `field_4` int(10) unsigned NOT NULL DEFAULT '0',
  `field_5` int(10) unsigned NOT NULL DEFAULT '0',
  `field_6` int(10) unsigned NOT NULL DEFAULT '0',
  `field_7` varchar(255) NOT NULL DEFAULT '',
  `field_8` varchar(255) NOT NULL DEFAULT '',
  `field_9` int(10) unsigned NOT NULL DEFAULT '0',
  `field_10` varchar(255) NOT NULL DEFAULT '',
  `field_11` varchar(255) NOT NULL DEFAULT '',
  `field_12` varchar(255) NOT NULL DEFAULT '',
  `field_13` longtext NOT NULL,
  `field_14` varchar(255) NOT NULL DEFAULT '',
  `field_15` longtext NOT NULL,
  `field_16` varchar(255) NOT NULL DEFAULT '',
  `field_17` varchar(255) NOT NULL DEFAULT '',
  `field_18` varchar(255) NOT NULL DEFAULT '',
  `field_19` varchar(255) NOT NULL DEFAULT '',
  `field_20` varchar(255) NOT NULL DEFAULT '',
  `field_21` varchar(255) NOT NULL DEFAULT '',
  `field_22` varchar(255) NOT NULL DEFAULT '',
  `field_23` longtext NOT NULL,
  `field_24` varchar(255) NOT NULL DEFAULT '',
  `field_25` varchar(255) NOT NULL DEFAULT '',
  `field_26` varchar(255) NOT NULL DEFAULT '',
  `field_27` longtext NOT NULL,
  `field_28` varchar(255) NOT NULL DEFAULT '',
  `field_29` varchar(255) NOT NULL DEFAULT '',
  `field_30` varchar(255) NOT NULL DEFAULT '',
  `field_31` varchar(255) NOT NULL DEFAULT '',
  `field_32` varchar(255) NOT NULL DEFAULT '',
  `field_33` varchar(255) NOT NULL DEFAULT '',
  `field_34` varchar(255) NOT NULL DEFAULT '',
  `field_35` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`mf_member_id`),
  FULLTEXT KEY `mcf2` (`field_2`),
  FULLTEXT KEY `mcf7` (`field_7`),
  FULLTEXT KEY `mcf8` (`field_8`),
  FULLTEXT KEY `mcf10` (`field_10`),
  FULLTEXT KEY `mcf13` (`field_13`),
  FULLTEXT KEY `mcf14` (`field_14`),
  FULLTEXT KEY `mcf15` (`field_15`),
  FULLTEXT KEY `mcf17` (`field_17`),
  FULLTEXT KEY `mcf18` (`field_18`),
  FULLTEXT KEY `mcf19` (`field_19`),
  FULLTEXT KEY `mcf20` (`field_20`),
  FULLTEXT KEY `mcf21` (`field_21`),
  FULLTEXT KEY `mcf22` (`field_22`),
  FULLTEXT KEY `mcf23` (`field_23`),
  FULLTEXT KEY `mcf24` (`field_24`),
  FULLTEXT KEY `mcf25` (`field_25`),
  FULLTEXT KEY `mcf26` (`field_26`),
  FULLTEXT KEY `mcf27` (`field_27`),
  FULLTEXT KEY `mcf33` (`field_33`),
  FULLTEXT KEY `mcf34` (`field_34`),
  FULLTEXT KEY `mcf35` (`field_35`)
) ENGINE=MyISAM CHARACTER SET=latin1;

insert into `ocp_f_member_custom_fields` values('1','69','','70','71','72','73','','','74','','','','','','','','','','','','','','','','','','','','','','','','','',''),
 ('2','77','','78','79','80','81','','','82','','','','','','','','','','','','','','','','','','','','','','','','','',''),
 ('3','85','','86','87','88','89','','','90','','','','','','','','','','','','','','','','','','','','','','','','','','');

DROP TABLE IF EXISTS `ocp_f_member_known_login_ips`;

CREATE TABLE `ocp_f_member_known_login_ips` (
  `i_member_id` int(11) NOT NULL,
  `i_ip` varchar(40) NOT NULL,
  `i_val_code` varchar(255) NOT NULL,
  PRIMARY KEY (`i_member_id`,`i_ip`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_members`;

CREATE TABLE `ocp_f_members` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `m_username` varchar(80) NOT NULL,
  `m_pass_hash_salted` varchar(255) NOT NULL,
  `m_pass_salt` varchar(255) NOT NULL,
  `m_theme` varchar(80) NOT NULL,
  `m_avatar_url` varchar(255) NOT NULL,
  `m_validated` tinyint(1) NOT NULL,
  `m_validated_email_confirm_code` varchar(255) NOT NULL,
  `m_cache_num_posts` int(11) NOT NULL,
  `m_cache_warnings` int(11) NOT NULL,
  `m_join_time` int(10) unsigned NOT NULL,
  `m_timezone_offset` varchar(255) NOT NULL,
  `m_primary_group` int(11) NOT NULL,
  `m_last_visit_time` int(10) unsigned NOT NULL,
  `m_last_submit_time` int(10) unsigned NOT NULL,
  `m_signature` int(10) unsigned NOT NULL,
  `m_is_perm_banned` tinyint(1) NOT NULL,
  `m_preview_posts` tinyint(1) NOT NULL,
  `m_dob_day` int(11) DEFAULT NULL,
  `m_dob_month` int(11) DEFAULT NULL,
  `m_dob_year` int(11) DEFAULT NULL,
  `m_reveal_age` tinyint(1) NOT NULL,
  `m_email_address` varchar(255) NOT NULL,
  `m_title` varchar(255) NOT NULL,
  `m_photo_url` varchar(255) NOT NULL,
  `m_photo_thumb_url` varchar(255) NOT NULL,
  `m_views_signatures` tinyint(1) NOT NULL,
  `m_auto_monitor_contrib_content` tinyint(1) NOT NULL,
  `m_language` varchar(80) NOT NULL,
  `m_ip_address` varchar(40) NOT NULL,
  `m_allow_emails` tinyint(1) NOT NULL,
  `m_allow_emails_from_staff` tinyint(1) NOT NULL,
  `m_notes` longtext NOT NULL,
  `m_zone_wide` tinyint(1) NOT NULL,
  `m_highlighted_name` tinyint(1) NOT NULL,
  `m_pt_allow` varchar(255) NOT NULL,
  `m_pt_rules_text` int(10) unsigned NOT NULL,
  `m_max_email_attach_size_mb` int(11) NOT NULL,
  `m_password_change_code` varchar(255) NOT NULL,
  `m_password_compat_scheme` varchar(80) NOT NULL,
  `m_on_probation_until` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_list` (`m_username`),
  KEY `menail` (`m_email_address`),
  KEY `external_auth_lookup` (`m_pass_hash_salted`),
  KEY `sort_post_count` (`m_cache_num_posts`),
  KEY `m_join_time` (`m_join_time`),
  KEY `whos_validated` (`m_validated`),
  KEY `birthdays` (`m_dob_day`,`m_dob_month`),
  KEY `ftjoin_msig` (`m_signature`),
  KEY `primary_group` (`m_primary_group`),
  KEY `avatar_url` (`m_avatar_url`),
  FULLTEXT KEY `search_user` (`m_username`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=4;

insert into `ocp_f_members` values('1','Guest','226f830908986be7514d75d37bb428ce','4f661710b40d1','','','1','','0','0','1332090640','UTC','1','1332090640','1332090640','67','0','1',null,null,null,'1','','','','','1','0','','192.168.1.64','1','1','','1','0','*','68','5','','',null),
 ('2','admin','cbc2d72ac60f321e7fdcd08ab5adb37c','4f661710bbca2','','themes/default/images/ocf_default_avatars/default_set/cool_flare.png','1','','0','0','1332090640','UTC','2','1332090640','1332090640','75','0','0',null,null,null,'1','','','','','1','1','','192.168.1.64','1','1','','1','0','*','76','5','','',null),
 ('3','test','76b5c7fc1ef42a0eab75edbe496b5010','4f661710bcc01','','','1','','0','0','1332090640','UTC','9','1332090640','1332090640','83','0','0',null,null,null,'1','','','','','1','0','','192.168.1.64','1','1','','1','0','*','84','5','','',null);

DROP TABLE IF EXISTS `ocp_f_moderator_logs`;

CREATE TABLE `ocp_f_moderator_logs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `l_the_type` varchar(80) NOT NULL,
  `l_param_a` varchar(255) NOT NULL,
  `l_param_b` varchar(255) NOT NULL,
  `l_date_and_time` int(10) unsigned NOT NULL,
  `l_reason` longtext NOT NULL,
  `l_by` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_multi_moderations`;

CREATE TABLE `ocp_f_multi_moderations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mm_name` int(10) unsigned NOT NULL,
  `mm_post_text` longtext NOT NULL,
  `mm_move_to` int(11) DEFAULT NULL,
  `mm_pin_state` tinyint(1) DEFAULT NULL,
  `mm_sink_state` tinyint(1) DEFAULT NULL,
  `mm_open_state` tinyint(1) DEFAULT NULL,
  `mm_forum_multi_code` varchar(255) NOT NULL,
  `mm_title_suffix` varchar(255) NOT NULL,
  PRIMARY KEY (`id`,`mm_name`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=2;

insert into `ocp_f_multi_moderations` values('1','66','','4','0','0','0','*','');

DROP TABLE IF EXISTS `ocp_f_poll_answers`;

CREATE TABLE `ocp_f_poll_answers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pa_poll_id` int(11) NOT NULL,
  `pa_answer` varchar(255) NOT NULL,
  `pa_cache_num_votes` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_poll_votes`;

CREATE TABLE `ocp_f_poll_votes` (
  `pv_poll_id` int(11) NOT NULL,
  `pv_member_id` int(11) NOT NULL,
  `pv_answer_id` int(11) NOT NULL,
  PRIMARY KEY (`pv_poll_id`,`pv_member_id`,`pv_answer_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_polls`;

CREATE TABLE `ocp_f_polls` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `po_question` varchar(255) NOT NULL,
  `po_cache_total_votes` int(11) NOT NULL,
  `po_is_private` tinyint(1) NOT NULL,
  `po_is_open` tinyint(1) NOT NULL,
  `po_minimum_selections` int(11) NOT NULL,
  `po_maximum_selections` int(11) NOT NULL,
  `po_requires_reply` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_post_history`;

CREATE TABLE `ocp_f_post_history` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `h_create_date_and_time` int(10) unsigned NOT NULL,
  `h_action_date_and_time` int(10) unsigned NOT NULL,
  `h_owner_member_id` int(11) NOT NULL,
  `h_alterer_member_id` int(11) NOT NULL,
  `h_post_id` int(11) NOT NULL,
  `h_topic_id` int(11) NOT NULL,
  `h_before` longtext NOT NULL,
  `h_action` varchar(80) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `phistorylookup` (`h_post_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_post_templates`;

CREATE TABLE `ocp_f_post_templates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `t_title` varchar(255) NOT NULL,
  `t_text` longtext NOT NULL,
  `t_forum_multi_code` varchar(255) NOT NULL,
  `t_use_default_forums` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=4;

insert into `ocp_f_post_templates` values('1','Bug report','Version: ?\nSupport software environment (operating system, etc.):\n?\n\nAssigned to: ?\nSeverity: ?\nExample URL: ?\nDescription:\n?\n\nSteps for reproduction:\n?\n\n','','0'),
 ('2','Task','Assigned to: ?\nPriority/Timescale: ?\nDescription:\n?\n\n','','0'),
 ('3','Fault','Version: ?\nAssigned to: ?\nSeverity/Timescale: ?\nDescription:\n?\n\nSteps for reproduction:\n?\n\n','','0');

DROP TABLE IF EXISTS `ocp_f_posts`;

CREATE TABLE `ocp_f_posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `p_title` varchar(255) NOT NULL,
  `p_post` int(10) unsigned NOT NULL,
  `p_ip_address` varchar(40) NOT NULL,
  `p_time` int(10) unsigned NOT NULL,
  `p_poster` int(11) NOT NULL,
  `p_intended_solely_for` int(11) DEFAULT NULL,
  `p_poster_name_if_guest` varchar(80) NOT NULL,
  `p_validated` tinyint(1) NOT NULL,
  `p_topic_id` int(11) NOT NULL,
  `p_cache_forum_id` int(11) DEFAULT NULL,
  `p_last_edit_time` int(10) unsigned DEFAULT NULL,
  `p_last_edit_by` int(11) DEFAULT NULL,
  `p_is_emphasised` tinyint(1) NOT NULL,
  `p_skip_sig` tinyint(1) NOT NULL,
  `p_parent_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `p_validated` (`p_validated`),
  KEY `in_topic` (`p_topic_id`,`p_time`,`id`),
  KEY `post_order_time` (`p_time`,`id`),
  KEY `p_last_edit_time` (`p_last_edit_time`),
  KEY `posts_by` (`p_poster`),
  KEY `find_pp` (`p_intended_solely_for`),
  KEY `search_join` (`p_post`),
  KEY `postsinforum` (`p_cache_forum_id`),
  KEY `deletebyip` (`p_ip_address`),
  FULLTEXT KEY `p_title` (`p_title`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=2;

insert into `ocp_f_posts` values('1','Welcome to the forums','91','127.0.0.1','1332090641','1',null,'System','1','1','7',null,null,'0','0',null);

DROP TABLE IF EXISTS `ocp_f_read_logs`;

CREATE TABLE `ocp_f_read_logs` (
  `l_member_id` int(11) NOT NULL,
  `l_topic_id` int(11) NOT NULL,
  `l_time` int(10) unsigned NOT NULL,
  PRIMARY KEY (`l_member_id`,`l_topic_id`),
  KEY `erase_old_read_logs` (`l_time`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_saved_warnings`;

CREATE TABLE `ocp_f_saved_warnings` (
  `s_title` varchar(255) NOT NULL,
  `s_explanation` longtext NOT NULL,
  `s_message` longtext NOT NULL,
  PRIMARY KEY (`s_title`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_special_pt_access`;

CREATE TABLE `ocp_f_special_pt_access` (
  `s_member_id` int(11) NOT NULL,
  `s_topic_id` int(11) NOT NULL,
  PRIMARY KEY (`s_member_id`,`s_topic_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_topics`;

CREATE TABLE `ocp_f_topics` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `t_pinned` tinyint(1) NOT NULL,
  `t_sunk` tinyint(1) NOT NULL,
  `t_cascading` tinyint(1) NOT NULL,
  `t_forum_id` int(11) DEFAULT NULL,
  `t_pt_from` int(11) DEFAULT NULL,
  `t_pt_to` int(11) DEFAULT NULL,
  `t_pt_from_category` varchar(255) NOT NULL,
  `t_pt_to_category` varchar(255) NOT NULL,
  `t_description` varchar(255) NOT NULL,
  `t_description_link` varchar(255) NOT NULL,
  `t_emoticon` varchar(255) NOT NULL,
  `t_num_views` int(11) NOT NULL,
  `t_validated` tinyint(1) NOT NULL,
  `t_is_open` tinyint(1) NOT NULL,
  `t_poll_id` int(11) DEFAULT NULL,
  `t_cache_first_post_id` int(11) DEFAULT NULL,
  `t_cache_first_time` int(10) unsigned DEFAULT NULL,
  `t_cache_first_title` varchar(255) NOT NULL,
  `t_cache_first_post` int(10) unsigned DEFAULT NULL,
  `t_cache_first_username` varchar(80) NOT NULL,
  `t_cache_first_member_id` int(11) DEFAULT NULL,
  `t_cache_last_post_id` int(11) DEFAULT NULL,
  `t_cache_last_time` int(10) unsigned DEFAULT NULL,
  `t_cache_last_title` varchar(255) NOT NULL,
  `t_cache_last_username` varchar(80) NOT NULL,
  `t_cache_last_member_id` int(11) DEFAULT NULL,
  `t_cache_num_posts` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `t_num_views` (`t_num_views`),
  KEY `t_pt_to` (`t_pt_to`),
  KEY `t_pt_from` (`t_pt_from`),
  KEY `t_validated` (`t_validated`),
  KEY `in_forum` (`t_forum_id`),
  KEY `topic_order_time` (`t_cache_last_time`),
  KEY `topic_order_time_2` (`t_cache_first_time`),
  KEY `descriptionsearch` (`t_description`),
  KEY `forumlayer` (`t_cache_first_title`),
  KEY `t_cascading` (`t_cascading`),
  KEY `t_cascading_or_forum` (`t_cascading`,`t_forum_id`),
  KEY `topic_order` (`t_cascading`,`t_pinned`,`t_cache_last_time`),
  KEY `topic_order_2` (`t_forum_id`,`t_cascading`,`t_pinned`,`t_sunk`,`t_cache_last_time`),
  KEY `topic_order_3` (`t_forum_id`,`t_cascading`,`t_pinned`,`t_cache_last_time`),
  KEY `ownedtopics` (`t_cache_first_member_id`),
  FULLTEXT KEY `t_description` (`t_description`)
) ENGINE=MyISAM CHARACTER SET=latin1 AUTO_INCREMENT=2;

insert into `ocp_f_topics` values('1','0','0','0','7',null,null,'','','','','','0','1','1',null,'1','1332090641','Welcome to the forums','91','System','1','1','1332090641','Welcome to the forums','System','1','1');

DROP TABLE IF EXISTS `ocp_f_usergroup_subs`;

CREATE TABLE `ocp_f_usergroup_subs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `s_title` int(10) unsigned NOT NULL,
  `s_description` int(10) unsigned NOT NULL,
  `s_cost` varchar(255) NOT NULL,
  `s_length` int(11) NOT NULL,
  `s_length_units` varchar(255) NOT NULL,
  `s_group_id` int(11) NOT NULL,
  `s_enabled` tinyint(1) NOT NULL,
  `s_mail_start` int(10) unsigned NOT NULL,
  `s_mail_end` int(10) unsigned NOT NULL,
  `s_mail_uhoh` int(10) unsigned NOT NULL,
  `s_uses_primary` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_warnings`;

CREATE TABLE `ocp_f_warnings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `w_member_id` int(11) NOT NULL,
  `w_time` int(10) unsigned NOT NULL,
  `w_explanation` longtext NOT NULL,
  `w_by` int(11) NOT NULL,
  `w_is_warning` tinyint(1) NOT NULL,
  `p_silence_from_topic` int(11) DEFAULT NULL,
  `p_silence_from_forum` int(11) DEFAULT NULL,
  `p_probation` int(11) NOT NULL,
  `p_banned_ip` varchar(40) NOT NULL,
  `p_charged_points` int(11) NOT NULL,
  `p_banned_member` tinyint(1) NOT NULL,
  `p_changed_usergroup_from` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `warningsmemberid` (`w_member_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_f_welcome_emails`;

CREATE TABLE `ocp_f_welcome_emails` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `w_name` varchar(255) NOT NULL,
  `w_subject` int(10) unsigned NOT NULL,
  `w_text` int(10) unsigned NOT NULL,
  `w_send_time` int(11) NOT NULL,
  `w_newsletter` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_feature_lifetime_monitor`;

CREATE TABLE `ocp_feature_lifetime_monitor` (
  `content_id` varchar(80) NOT NULL,
  `block_cache_id` varchar(80) NOT NULL,
  `run_period` int(11) NOT NULL,
  `running_now` tinyint(1) NOT NULL,
  `last_update` int(10) unsigned NOT NULL,
  PRIMARY KEY (`content_id`,`block_cache_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_filedump`;

CREATE TABLE `ocp_filedump` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `path` varchar(255) NOT NULL,
  `description` int(10) unsigned NOT NULL,
  `the_member` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_galleries`;

CREATE TABLE `ocp_galleries` (
  `name` varchar(80) NOT NULL,
  `description` int(10) unsigned NOT NULL,
  `teaser` int(10) unsigned NOT NULL,
  `fullname` int(10) unsigned NOT NULL,
  `add_date` int(10) unsigned NOT NULL,
  `rep_image` varchar(255) NOT NULL,
  `parent_id` varchar(80) NOT NULL,
  `watermark_top_left` varchar(255) NOT NULL,
  `watermark_top_right` varchar(255) NOT NULL,
  `watermark_bottom_left` varchar(255) NOT NULL,
  `watermark_bottom_right` varchar(255) NOT NULL,
  `accept_images` tinyint(1) NOT NULL,
  `accept_videos` tinyint(1) NOT NULL,
  `allow_rating` tinyint(1) NOT NULL,
  `allow_comments` tinyint(4) NOT NULL,
  `notes` longtext NOT NULL,
  `is_member_synched` tinyint(1) NOT NULL,
  `flow_mode_interface` tinyint(1) NOT NULL,
  `gallery_views` int(11) NOT NULL,
  `g_owner` int(11) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `watermark_top_left` (`watermark_top_left`),
  KEY `watermark_top_right` (`watermark_top_right`),
  KEY `watermark_bottom_left` (`watermark_bottom_left`),
  KEY `watermark_bottom_right` (`watermark_bottom_right`),
  KEY `gadd_date` (`add_date`),
  KEY `parent_id` (`parent_id`),
  KEY `ftjoin_gfullname` (`fullname`),
  KEY `ftjoin_gdescrip` (`description`)
) ENGINE=MyISAM CHARACTER SET=latin1;

insert into `ocp_galleries` values('root','307','308','309','1332090696','','','','','','','1','1','1','1','','0','1','0',null);

DROP TABLE IF EXISTS `ocp_gifts`;

CREATE TABLE `ocp_gifts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date_and_time` int(10) unsigned NOT NULL,
  `amount` int(11) NOT NULL,
  `gift_from` int(11) NOT NULL,
  `gift_to` int(11) NOT NULL,
  `reason` int(10) unsigned NOT NULL,
  `anonymous` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `giftsgiven` (`gift_from`),
  KEY `giftsreceived` (`gift_to`)
) ENGINE=MyISAM CHARACTER SET=latin1;


DROP TABLE IF EXISTS `ocp_group_category_access`;

CREATE TABLE `ocp_group_category_access` (
  `module_the_name` varchar(80) NOT NULL,
  `category_name` varchar(80) NOT NULL,
  `group_id` int(11) NOT NULL,
  PRIMARY KEY (`module_the_name`,`category_name`,`group_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;

insert into `ocp_group_category_access` values('banners','advertise_here','1'),
 ('banners','advertise_here','2'),
 ('banners','advertise_here','3'),
 ('banners','advertise_here','4'),
 ('banners','advertise_here','5'),
 ('banners','advertise_here','6'),
 ('banners','advertise_here','7'),
 ('banners','advertise_here','8'),
 ('banners','advertise_here','9'),
 ('banners','advertise_here','10'),
 ('banners','donate','1'),
 ('banners','donate','2'),
 ('banners','donate','3'),
 ('banners','donate','4'),
 ('banners','donate','5'),
 ('banners','donate','6'),
 ('banners','donate','7'),
 ('banners','donate','8'),
 ('banners','donate','9'),
 ('banners','donate','10'),
 ('catalogues_catalogue','faqs','1'),
 ('catalogues_catalogue','faqs','2'),
 ('catalogues_catalogue','faqs','3'),
 ('catalogues_catalogue','faqs','4'),
 ('catalogues_catalogue','faqs','5'),
 ('catalogues_catalogue','faqs','6'),
 ('catalogues_catalogue','faqs','7'),
 ('catalogues_catalogue','faqs','8'),
 ('catalogues_catalogue','faqs','9'),
 ('catalogues_catalogue','faqs','10'),
 ('catalogues_catalogue','hosted','1'),
 ('catalogues_catalogue','hosted','2'),
 ('catalogues_catalogue','hosted','3'),
 ('catalogues_catalogue','hosted','4'),
 ('catalogues_catalogue','hosted','5'),
 ('catalogues_catalogue','hosted','6'),
 ('catalogues_catalogue','hosted','7'),
 ('catalogues_catalogue','hosted','8'),
 ('catalogues_catalogue','hosted','9'),
 ('catalogues_catalogue','hosted','10'),
 ('catalogues_catalogue','links','1'),
 ('catalogues_catalogue','links','2'),
 ('catalogues_catalogue','links','3'),
 ('catalogues_catalogue','links','4'),
 ('catalogues_catalogue','links','5'),
 ('catalogues_catalogue','links','6'),
 ('catalogues_catalogue','links','7'),
 ('catalogues_catalogue','links','8'),
 ('catalogues_catalogue','links','9'),
 ('catalogues_catalogue','links','10'),
 ('catalogues_catalogue','modifications','1'),
 ('catalogues_catalogue','modifications','2'),
 ('catalogues_catalogue','modifications','3'),
 ('catalogues_catalogue','modifications','4'),
 ('catalogues_catalogue','modifications','5'),
 ('catalogues_catalogue','modifications','6'),
 ('catalogues_catalogue','modifications','7'),
 ('catalogues_catalogue','modifications','8'),
 ('catalogues_catalogue','modifications','9'),
 ('catalogues_catalogue','modifications','10'),
 ('catalogues_catalogue','products','1'),
 ('catalogues_catalogue','products','2'),
 ('catalogues_catalogue','products','3'),
 ('catalogues_catalogue','products','4'),
 ('catalogues_catalogue','products','5'),
 ('catalogues_catalogue','products','6'),
 ('catalogues_catalogue','products','7'),
 ('catalogues_catalogue','products','8'),
 ('catalogues_catalogue','products','9'),
 ('catalogues_catalogue','products','10'),
 ('catalogues_catalogue','projects','1'),
 ('catalogues_catalogue','projects','2'),
 ('catalogues_catalogue','projects','3'),
 ('catalogues_catalogue','projects','4'),
 ('catalogues_catalogue','projects','5'),
 ('catalogues_catalogue','projects','6'),
 ('catalogues_catalogue','projects','7'),
 ('catalogues_catalogue','projects','8'),
 ('catalogues_catalogue','projects','9'),
 ('catalogues_catalogue','projects','10'),
 ('catalogues_category','1','1'),
 ('catalogues_category','1','2'),
 ('catalogues_category','1','3'),
 ('catalogues_category','1','4'),
 ('catalogues_category','1','5'),
 ('catalogues_category','1','6'),
 ('catalogues_category','1','7'),
 ('catalogues_category','1','8'),
 ('catalogues_category','1','9'),
 ('catalogues_category','1','10'),
 ('catalogues_category','2','1'),
 ('catalogues_category','2','2'),
 ('catalogues_category','2','3'),
 ('catalogues_category','2','4'),
 ('catalogues_category','2','5'),
 ('catalogues_category','2','6'),
 ('catalogues_category','2','7'),
 ('catalogues_category','2','8'),
 ('catalogues_category','2','9'),
 ('catalogues_category','2','10'),
 ('catalogues_category','3','1'),
 ('catalogues_category','3','2'),
 ('catalogues_category','3','3'),
 ('catalogues_category','3','4'),
 ('catalogues_category','3','5'),
 ('catalogues_category','3','6'),
 ('catalogues_category','3','7'),
 ('catalogues_category','3','8'),
 ('catalogues_category','3','9'),
 ('catalogues_category','3','10'),
 ('catalogues_category','4','1'),
 ('catalogues_category','4','2'),
 ('catalogues_category','4','3'),
 ('catalogues_category','4','4'),
 ('catalogues_category','4','5'),
 ('catalogues_category','4','6'),
 ('catalogues_category','4','7'),
 ('catalogues_category','4','8'),
 ('catalogues_category','4','9'),
 ('catalogues_category','4','10'),
 ('catalogues_category','6','1'),
 ('catalogues_category','6','2'),
 ('catalogues_category','6','3'),
 ('catalogues_category','6','4'),
 ('catalogues_category','6','5'),
 ('catalogues_category','6','6'),
 ('catalogues_category','6','7'),
 ('catalogues_category','6','8'),
 ('catalogues_category','6','9'),
 ('catalogues_category','6','10'),
 ('chat','1','1'),
 ('chat','1','3'),
 ('chat','1','4'),
 ('chat','1','5'),
 ('chat','1','6'),
 ('chat','1','7'),
 ('chat','1','8'),
 ('chat','1','9'),
 ('chat','1','10'),
 ('downloads','1','1'),
 ('downloads','1','2'),
 ('downloads','1','3'),
 ('downloads','1','4'),
 ('downloads','1','5'),
 ('downloads','1','6'),
 ('downloads','1','7'),
 ('downloads','1','8'),
 ('downloads','1','9'),
 ('downloads','1','10'),
 ('forums','1','1'),
 ('forums','1','2'),
 ('forums','1','3'),
 ('forums','1','4'),
 ('forums','1','5'),
 ('forums','1','6'),
 ('forums','1','7'),
 ('forums','1','8'),
 ('forums','1','9'),
 ('forums','1','10'),
 ('forums','2','1'),
 ('forums','2','2'),
 ('forums','2','3'),
 ('forums','2','4'),
 ('forums','2','5'),
 ('forums','2','6'),
 ('forums','2','7'),
 ('forums','2','8'),
 ('forums','2','9'),
 ('forums','2','10'),
 ('forums','3','2'),
 ('forums','3','3'),
 ('forums','4','2'),
 ('forums','4','3'),
 ('forums','5','1'),
 ('forums','5','2'),
 ('forums','5','3'),
 ('forums','5','4'),
 ('forums','5','5'),
 ('forums','5','6'),
 ('forums','5','7'),
 ('forums','5','8'),
 ('forums','5','9'),
 ('forums','5','10'),
 ('forums','6','2'),
 ('forums','6','3'),
 ('forums','7','2'),
 ('forums','7','3'),
 ('forums','8','3'),
 ('galleries','root','1'),
 ('galleries','root','2'),
 ('galleries','root','3'),
 ('galleries','root','4'),
 ('galleries','root','5'),
 ('galleries','root','6'),
 ('galleries','root','7'),
 ('galleries','root','8'),
 ('galleries','root','9'),
 ('galleries','root','10'),
 ('news','1','1'),
 ('news','1','2'),
 ('news','1','3'),
 ('news','1','4'),
 ('news','1','5'),
 ('news','1','6'),
 ('news','1','7'),
 ('news','1','8'),
 ('news','1','9'),
 ('news','1','10'),
 ('news','2','1'),
 ('news','2','2'),
 ('news','2','3'),
 ('news','2','4'),
 ('news','2','5'),
 ('news','2','6'),
 ('news','2','7'),
 ('news','2','8'),
 ('news','2','9'),
 ('news','2','10'),
 ('news','3','1'),
 ('news','3','2'),
 ('news','3','3'),
 ('news','3','4'),
 ('news','3','5'),
 ('news','3','6'),
 ('news','3','7'),
 ('news','3','8'),
 ('news','3','9'),
 ('news','3','10'),
 ('news','4','1'),
 ('news','4','2'),
 ('news','4','3'),
 ('news','4','4'),
 ('news','4','5'),
 ('news','4','6'),
 ('news','4','7'),
 ('news','4','8'),
 ('news','4','9'),
 ('news','4','10'),
 ('news','5','1'),
 ('news','5','2'),
 ('news','5','3'),
 ('news','5','4'),
 ('news','5','5'),
 ('news','5','6'),
 ('news','5','7'),
 ('news','5','8'),
 ('news','5','9'),
 ('news','5','10'),
 ('news','6','1'),
 ('news','6','2'),
 ('news','6','3'),
 ('news','6','4'),
 ('news','6','5'),
 ('news','6','6'),
 ('news','6','7'),
 ('news','6','8'),
 ('news','6','9'),
 ('news','6','10'),
 ('news','7','1'),
 ('news','7','2'),
 ('news','7','3'),
 ('news','7','4'),
 ('news','7','5'),
 ('news','7','6'),
 ('news','7','7'),
 ('news','7','8'),
 ('news','7','9'),
 ('news','7','10'),
 ('seedy_page','1','1'),
 ('seedy_page','1','2'),
 ('seedy_page','1','3'),
 ('seedy_page','1','4'),
 ('seedy_page','1','5'),
 ('seedy_page','1','6'),
 ('seedy_page','1','7'),
 ('seedy_page','1','8'),
 ('seedy_page','1','9'),
 ('seedy_page','1','10'),
 ('tickets','Complaint','1'),
 ('tickets','Complaint','2'),
 ('tickets','Complaint','3'),
 ('tickets','Complaint','4'),
 ('tickets','Complaint','5'),
 ('tickets','Complaint','6'),
 ('tickets','Complaint','7'),
 ('tickets','Complaint','8'),
 ('tickets','Complaint','9'),
 ('tickets','Complaint','10'),
 ('tickets','Other','1'),
 ('tickets','Other','2'),
 ('tickets','Other','3'),
 ('tickets','Other','4'),
 ('tickets','Other','5'),
 ('tickets','Other','6'),
 ('tickets','Other','7'),
 ('tickets','Other','8'),
 ('tickets','Other','9'),
 ('tickets','Other','10');

DROP TABLE IF EXISTS `ocp_group_page_access`;

CREATE TABLE `ocp_group_page_access` (
  `page_name` varchar(80) NOT NULL,
  `zone_name` varchar(80) NOT NULL,
  `group_id` int(11) NOT NULL,
  PRIMARY KEY (`page_name`,`zone_name`,`group_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;

insert into `ocp_group_page_access` values('admin_addons','adminzone','1'),
 ('admin_addons','adminzone','2'),
 ('admin_addons','adminzone','3'),
 ('admin_addons','adminzone','4'),
 ('admin_addons','adminzone','5'),
 ('admin_addons','adminzone','6'),
 ('admin_addons','adminzone','7'),
 ('admin_addons','adminzone','8'),
 ('admin_addons','adminzone','9'),
 ('admin_addons','adminzone','10'),
 ('admin_emaillog','adminzone','1'),
 ('admin_emaillog','adminzone','2'),
 ('admin_emaillog','adminzone','3'),
 ('admin_emaillog','adminzone','4'),
 ('admin_emaillog','adminzone','5'),
 ('admin_emaillog','adminzone','6'),
 ('admin_emaillog','adminzone','7'),
 ('admin_emaillog','adminzone','8'),
 ('admin_emaillog','adminzone','9'),
 ('admin_emaillog','adminzone','10'),
 ('admin_import','adminzone','1'),
 ('admin_import','adminzone','2'),
 ('admin_import','adminzone','3'),
 ('admin_import','adminzone','4'),
 ('admin_import','adminzone','5'),
 ('admin_import','adminzone','6'),
 ('admin_import','adminzone','7'),
 ('admin_import','adminzone','8'),
 ('admin_import','adminzone','9'),
 ('admin_import','adminzone','10'),
 ('admin_occle','adminzone','1'),
 ('admin_occle','adminzone','2'),
 ('admin_occle','adminzone','3'),
 ('admin_occle','adminzone','4'),
 ('admin_occle','adminzone','5'),
 ('admin_occle','adminzone','6'),
 ('admin_occle','adminzone','7'),
 ('admin_occle','adminzone','8'),
 ('admin_occle','adminzone','9'),
 ('admin_occle','adminzone','10'),
 ('admin_redirects','adminzone','1'),
 ('admin_redirects','adminzone','2'),
 ('admin_redirects','adminzone','3'),
 ('admin_redirects','adminzone','4'),
 ('admin_redirects','adminzone','5'),
 ('admin_redirects','adminzone','6'),
 ('admin_redirects','adminzone','7'),
 ('admin_redirects','adminzone','8'),
 ('admin_redirects','adminzone','9'),
 ('admin_redirects','adminzone','10'),
 ('admin_staff','adminzone','1'),
 ('admin_staff','adminzone','2'),
 ('admin_staff','adminzone','3'),
 ('admin_staff','adminzone','4'),
 ('admin_staff','adminzone','5'),
 ('admin_staff','adminzone','6'),
 ('admin_staff','adminzone','7'),
 ('admin_staff','adminzone','8'),
 ('admin_staff','adminzone','9'),
 ('admin_staff','adminzone','10'),
 ('cms_chat','cms','1'),
 ('cms_chat','cms','2'),
 ('cms_chat','cms','3'),
 ('cms_chat','cms','4'),
 ('cms_chat','cms','5'),
 ('cms_chat','cms','6'),
 ('cms_chat','cms','7'),
 ('cms_chat','cms','8'),
 ('cms_chat','cms','9'),
 ('cms_chat','cms','10');

DROP TABLE IF EXISTS `ocp_group_zone_access`;

CREATE TABLE `ocp_group_zone_access` (
  `zone_name` varchar(80) NOT NULL,
  `group_id` int(11) NOT NULL,
  PRIMARY KEY (`zone_name`,`group_id`),
  KEY `group_id` (`group_id`)
) ENGINE=MyISAM CHARACTER SET=latin1;

insert into `ocp_group_zone_access` values('','1'),
 ('','2'),
 ('','3'),
 ('','4'),
 ('','5'),
 ('','6'),
 ('','7'),
 ('','8'),
 ('','9'),
 ('','10'),
 ('adminzone','2'),
 ('adminzone','3'),
 ('cms','2'),
 ('cms','3'),
 ('cms','4'),
 ('cms','5'),
 ('cms','6'),
 ('cms','7'),
 ('cms','8'),
 ('cms','9'),
 ('cms','10'),
 ('collaboration','2'),
 ('collaboration','3'),
 ('collaboration','4'),
 ('forum','1'),
 ('forum','2'),
 ('forum','3'),
 ('forum','4'),
 ('forum','5'),
 ('forum','6'),
 ('forum','7'),
 ('forum','8'),
 ('forum','9'),
 ('forum','10'),
 ('site','2'),
 ('site','3'),
 ('site','4'),
 ('site','5'),
 ('site','6'),
 ('site','7'),
 ('site','8'),
 ('site','9'),
 ('site','10');

DROP TABLE IF EXISTS `ocp_gsp`;

CREATE TABLE `ocp_gsp` (
  `group_id` int(11) NOT NULL,
  `specific_permission` varchar(80) NOT NULL,
  `the_page` varchar(80) NOT NULL,
  `module_the_name` varchar(80) NOT NULL,
  `category_name` varchar(80) NOT NULL,
  `the_value` tinyint(1) NOT NULL,
  PRIMARY KEY (`group_id`,`specific_permission`,`the_page`,`module_the_name`,`category_name`)
) ENGINE=MyISAM CHARACTER SET=latin1;

insert into `ocp_gsp` values('1','submit_lowrange_content','','forums','1','0'),
 ('1','submit_midrange_content','','forums','1','0'),
 ('2','bypass_validation_lowrange_content','','forums','1','1'),
 ('2','bypass_validation_midrange_content','','forums','1','1'),
 ('3','bypass_validation_lowrange_content','','forums','1','1'),
 ('3','bypass_validation_midrange_content','','forums','1','1'),
 ('5','submit_lowrange_content','','forums','1','0'),
 ('5','submit_midrange_content','','forums','1','0'),
 ('6','submit_lowrange_content','','forums','1','0'),
 ('6','submit_midrange_content','','forums','1','0'),
 ('7','submit_lowrange_content','','forums','1','0'),
 ('7','submit_midrange_content','','forums','1','0'),
 ('8','submit_lowrange_content','','forums','1','0'),
 ('8','submit_midrange_content','','forums','1','0'),
 ('9','submit_lowrange_content','','forums','1','0'),
 ('9','submit_midrange_content','','forums','1','0'),
 ('10','submit_lowrange_content','','forums','1','0'),
 ('10','submit_midrange_content','','forums','1','0'),
 ('1','bypass_validation_lowrange_content','','forums','2','1'),
 ('1','bypass_validation_midrange_content','','forums','2','1'),
 ('2','bypass_validation_lowrange_content','','forums','2','1'),
 ('2','bypass_validation_midrange_content','','forums','2','1'),
 ('3','bypass_validation_lowrange_content','','forums','2','1'),
 ('3','bypass_validation_midrange_content','','forums','2','1'),
 ('4','bypass_validation_lowrange_content','','forums','2','1'),
 ('4','bypass_validation_midrange_content','','forums','2','1'),
 ('5','bypass_validation_lowrange_content','','forums','2','1'),
 ('5','bypass_validation_midrange_content','','forums','2','1'),
 ('6','bypass_validation_lowrange_content','','forums','2','1'),
 ('6','bypass_validation_midrange_content','','forums','2','1'),
 ('7','bypass_validation_lowrange_content','','forums','2','1'),
 ('7','bypass_validation_midrange_content','','forums','2','1'),
 ('8','bypass_validation_lowrange_content','','forums','2','1'),
 ('8','bypass_validation_midrange_content','','forums','2','1'),
 ('9','bypass_validation_lowrange_content','','forums','2','1'),
 ('9','bypass_validation_midrange_content','','forums','2','1'),
 ('2','bypass_validation_lowrange_content','','forums','3','1'),
 ('2','bypass_validation_midrange_content','','forums','3','1'),
 ('3','bypass_validation_lowrange_content','','forums','3','1'),
 ('3','bypass_validation_midrange_content','','forums','3','1'),
 ('2','bypass_validation_lowrange_content','','forums','4','1'),
 ('2','bypass_validation_midrange_content','','forums','4','1'),
 ('3','bypass_validation_lowrange_content','','forums','4','1'),
 ('3','bypass_validation_midrange_content','','forums','4','1'),
 ('1','bypass_validation_lowrange_content','','forums','5','1'),
 ('1','bypass_validation_midrange_content','','forums','5','1'),
 ('2','bypass_validation_lowrange_content','','forums','5','1'),
 ('2','bypass_validation_midrange_content','','forums','5','1'),
 ('3','bypass_validation_lowrange_content','','forums','5','1'),
 ('3','bypass_validation_midrange_content','','forums','5','1'),
 ('4','bypass_validation_lowrange_content','','forums','5','1'),
 ('4','bypass_validation_midrange_content','','forums','5','1'),
 ('5','bypass_validation_lowrange_content','','forums','5','1'),
 ('5','bypass_validation_midrange_content','','forums','5','1'),
 ('6','bypass_validation_lowrange_content','','forums','5','1'),
 ('6','bypass_validation_midrange_content','','forums','5','1'),
 ('7','bypass_validation_lowrange_content','','forums','5','1'),
 ('7','bypass_validation_midrange_content','','forums','5','1'),
 ('8','bypass_validation_lowrange_content','','forums','5','1'),
 ('8','bypass_validation_midrange_content','','forums','5','1'),
 ('9','bypass_validation_lowrange_content','','forums','5','1'),
 ('9','bypass_validation_midrange_content','','forums','5','1'),
 ('2','bypass_validation_lowrange_content','','forums','6','1'),
 ('2','bypass_validation_midrange_content','','forums','6','1'),
 ('3','bypass_validation_lowrange_content','','forums','6','1'),
 ('3','bypass_validation_midrange_content','','forums','6','1'),
 ('2','bypass_validation_lowrange_content','','forums','7','1'),
 ('2','bypass_validation_midrange_content','','forums','7','1'),
 ('3','bypass_validation_lowrange_content','','forums','7','1'),
 ('3','bypass_validation_midrange_content','','forums','7','1'),
 ('1','run_multi_moderations','','','','1'),
 ('2','run_multi_moderations','','','','1'),
 ('3','run_multi_moderations','','','','1'),
 ('4','run_multi_moderations','','','','1'),
 ('5','run_multi_moderations','','','','1'),
 ('6','run_multi_moderations','','','','1'),
 ('7','run_multi_moderations','','','','1'),
 ('8','run_multi_moderations','','','','1'),
 ('9','run_multi_moderations','','','','1'),
 ('10','run_multi_moderations','','','','1'),
 ('1','use_pt','','','','1'),
 ('2','use_pt','','','','1'),
 ('3','use_pt','','','','1'),
 ('4','use_pt','','','','1'),
 ('5','use_pt','','','','1'),
 ('6','use_pt','','','','1'),
 ('7','use_pt','','','','1'),
 ('8','use_pt','','','','1'),
 ('9','use_pt','','','','1'),
 ('10','use_pt','','','','1'),
 ('1','edit_personal_topic_posts','','','','1'),
 ('2','edit_personal_topic_posts','','','','1'),
 ('3','edit_personal_topic_posts','','','','1'),
 ('4','edit_personal_topic_posts','','','','1'),
 ('5','edit_personal_topic_posts','','','','1'),
 ('6','edit_personal_topic_posts','','','','1'),
 ('7','edit_personal_topic_posts','','','','1'),
 ('8','edit_personal_topic_posts','','','','1'),
 ('9','edit_personal_topic_posts','','','','1'),
 ('10','edit_personal_topic_posts','','','','1'),
 ('1','may_unblind_own_poll','','','','1'),
 ('2','may_unblind_own_poll','','','','1'),
 ('3','may_unblind_own_poll','','','','1'),
 ('4','may_unblind_own_poll','','','','1'),
 ('5','may_unblind_own_poll','','','','1'),
 ('6','may_unblind_own_poll','','','','1'),
 ('7','may_unblind_own_poll','','','','1'),
 ('8','may_unblind_own_poll','','','','1'),
 ('9','may_unblind_own_poll','','','','1'),
 ('10','may_unblind_own_poll','','','','1'),
 ('1','may_report_post','','','','1'),
 ('2','may_report_post','','','','1'),
 ('3','may_report_post','','','','1'),
 ('4','may_report_post','','','','1'),
 ('5','may_report_post','','','','1'),
 ('6','may_report_post','','','','1'),
 ('7','may_report_post','','','','1'),
 ('8','may_report_post','','','','1'),
 ('9','may_report_post','','','','1'),
 ('10','may_report_post','','','','1'),
 ('1','view_member_photos','','','','1'),
 ('2','view_member_photos','','','','1'),
 ('3','view_member_photos','','','','1'),
 ('4','view_member_photos','','','','1'),
 ('5','view_member_photos','','','','1'),
 ('6','view_member_photos','','','','1'),
 ('7','view_member_photos','','','','1'),
 ('8','view_member_photos','','','','1'),
 ('9','view_member_photos','','','','1'),
 ('10','view_member_photos','','','','1'),
 ('1','use_quick_reply','','','','1'),
 ('2','use_quick_reply','','','','1'),
 ('3','use_quick_reply','','','','1'),
 ('4','use_quick_reply','','','','1'),
 ('5','use_quick_reply','','','','1'),
 ('6','use_quick_reply','','','','1'),
 ('7','use_quick_reply','','','','1'),
 ('8','use_quick_reply','','','','1'),
 ('9','use_quick_reply','','','','1'),
 ('10','use_quick_reply','','','','1'),
 ('1','view_profiles','','','','1'),
 ('2','view_profiles','','','','1'),
 ('3','view_profiles','','','','1'),
 ('4','view_profiles','','','','1'),
 ('5','view_profiles','','','','1'),
 ('6','view_profiles','','','','1'),
 ('7','view_profiles','','','','1'),
 ('8','view_profiles','','','','1'),
 ('9','view_profiles','','','','1'),
 ('10','view_profiles','','','','1'),
 ('1','own_avatars','','','','1'),
 ('2','own_avatars','','','','1'),
 ('3','own_avatars','','','','1'),
 ('4','own_avatars','','','','1'),
 ('5','own_avatars','','','','1'),
 ('6','own_avatars','','','','1'),
 ('7','own_avatars','','','','1'),
 ('8','own_avatars','','','','1'),
 ('9','own_avatars','','','','1'),
 ('10','own_avatars','','','','1'),
 ('3','rename_self','','','','1'),
 ('3','use_special_emoticons','','','','1'),
 ('3','view_any_profile_field','','','','1'),
 ('3','disable_lost_passwords','','','','1'),
 ('3','close_own_topics','','','','1'),
 ('3','edit_own_polls','','','','1'),
 ('3','double_post','','','','1'),
 ('3','see_warnings','','','','1'),
 ('3','see_ip','','','','1'),
 ('3','may_choose_custom_title','','','','1'),
 ('3','delete_account','','','','1'),
 ('3','view_poll_results_before_voting','','','','1'),
 ('3','moderate_personal_topic','','','','1'),
 ('3','member_maintenance','','','','1'),
 ('3','probate_members','','','','1'),
 ('3','warn_members','','','','1'),
 ('3','control_usergroups','','','','1'),
 ('3','multi_delete_topics','','','','1'),
 ('3','show_user_browsing','','','','1'),
 ('3','see_hidden_groups','','','','1'),
 ('3','pt_anyone','','','','1'),
 ('1','reuse_others_attachments','','','','1'),
 ('2','reuse_others_attachments','','','','1'),
 ('3','reuse_others_attachments','','','','1'),
 ('4','reuse_others_attachments','','','','1'),
 ('5','reuse_others_attachments','','','','1'),
 ('6','reuse_others_attachments','','','','1'),
 ('7','reuse_others_attachments','','','','1'),
 ('8','reuse_others_attachments','','','','1'),
 ('9','reuse_others_attachments','','','','1'),
 ('10','reuse_others_attachments','','','','1'),
 ('2','use_sms','','','','1'),
 ('3','use_sms','','','','1'),
 ('2','sms_higher_limit','','','','1'),
 ('3','sms_higher_limit','','','','1'),
 ('2','sms_higher_trigger_limit','','','','1'),
 ('3','sms_higher_trigger_limit','','','','1'),
 ('2','may_enable_staff_notifications','','','','1'),
 ('3','may_enable_staff_notifications','','','','1'),
 ('2','draw_to_server','','','','1'),
 ('3','draw_to_server','','','','1'),
 ('2','see_unvalidated','','','','1'),
 ('3','see_unvalidated','','','','1'),
 ('1','jump_to_unvalidated','','','','1'),
 ('2','jump_to_unvalidated','','','','1'),
 ('3','jump_to_unvalidated','','','','1'),
 ('4','jump_to_unvalidated','','','','1'),
 ('5','jump_to_unvalidated','','','','1'),
 ('6','jump_to_unvalidated','','','','1'),
 ('7','jump_to_unvalidated','','','','1'),
 ('8','jump_to_unvalidated','','','','1'),
 ('9','jump_to_unvalidated','','','','1'),
 ('10','jump_to_unvalidated','','','','1'),
 ('1','edit_own_lowrange_content','','','','1'),
 ('2','edit_own_lowrange_content','','','','1'),
 ('3','edit_own_lowrange_content','','','','1'),
 ('4','edit_own_lowrange_content','','','','1'),
 ('5','edit_own_lowrange_content','','','','1'),
 ('6','edit_own_lowrange_content','','','','1'),
 ('7','edit_own_lowrange_content','','','','1'),
 ('8','edit_own_lowrange_content','','','','1'),
 ('9','edit_own_lowrange_content','','','','1'),
 ('10','edit_own_lowrange_content','','','','1'),
 ('1','submit_highrange_content','','','','1'),
 ('2','submit_highrange_content','','','','1'),
 ('3','submit_highrange_content','','','','1'),
 ('4','submit_highrange_content','','','','1'),
 ('5','submit_highrange_content','','','','1'),
 ('6','submit_highrange_content','','','','1'),
 ('7','submit_highrange_content','','','','1'),
 ('8','submit_highrange_content','','','','1'),
 ('9','submit_highrange_content','','','','1'),
 ('10','submit_highrange_content','','','','1'),
 ('1','submit_midrange_content','','','','1'),
 ('2','submit_midrange_content','','','','1'),
 ('3','submit_midrange_content','','','','1'),
 ('4','submit_midrange_content','','','','1'),
 ('5','submit_midrange_content','','','','1'),
 ('6','submit_midrange_content','','','','1'),
 ('7','submit_midrange_content','','','','1'),
 ('8','submit_midrange_content','','','','1'),
 ('9','submit_midrange_content','','','','1'),
 ('10','submit_midrange_content','','','','1'),
 ('1','submit_lowrange_content','','','','1'),
 ('2','submit_lowrange_content','','','','1'),
 ('3','submit_lowrange_content','','','','1'),
 ('4','submit_lowrange_content','','','','1'),
 ('5','submit_lowrange_content','','','','1'),
 ('6','submit_lowrange_content','','','','1'),
 ('7','submit_lowrange_content','','','','1'),
 ('8','submit_lowrange_content','','','','1'),
 ('9','submit_lowrange_content','','','','1'),
 ('10','submit_lowrange_content','','','','1'),
 ('1','bypass_validation_lowrange_content','','','','1'),
 ('2','bypass_validation_lowrange_content','','','','1'),
 ('3','bypass_validation_lowrange_content','','','','1'),
 ('4','bypass_validation_lowrange_content','','','','1'),
 ('5','bypass_validation_lowrange_content','','','','1'),
 ('6','bypass_validation_lowrange_content','','','','1'),
 ('7','bypass_validation_lowrange_content','','','','1'),
 ('8','bypass_validation_lowrange_content','','','','1'),
 ('9','bypass_validation_lowrange_content','','','','1'),
 ('10','bypass_validation_lowrange_content','','','','1'),
 ('1','set_own_author_profile','','','','1'),
 ('2','set_own_author_profile','','','','1'),
 ('3','set_own_author_profile','','','','1'),
 ('4','set_own_author_profile','','','','1'),
 ('5','set_own_author_profile','','','','1'),
 ('6','set_own_author_profile','','','','1'),
 ('7','set_own_author_profile','','','','1'),
 ('8','set_own_author_profile','','','','1'),
 ('9','set_own_author_profile','','','','1'),
 ('10','set_own_author_profile','','','','1'),
 ('1','rate','','','','1'),
 ('2','rate','','','','1'),
 ('3','rate','','','','1'),
 ('4','rate','','','','1'),
 ('5','rate','','','','1'),
 ('6','rate','','','','1'),
 ('7','rate','','','','1'),
 ('8','rate','','','','1'),
 ('9','rate','','','','1'),
 ('10','rate','','','','1'),
 ('1','comment','','','','1'),
 ('2','comment','','','','1'),
 ('3','comment','','','','1'),
 ('4','comment','','','','1'),
 ('5','comment','','','','1'),
 ('6','comment','','','','1'),
 ('7','comment','','','','1'),
 ('8','comment','','','','1'),
 ('9','comment','','','','1'),
 ('10','comment','','','','1'),
 ('1','have_personal_category','','','','1'),
 ('2','have_personal_category','','','','1'),
 ('3','have_personal_category','','','','1'),
 ('4','have_personal_category','','','','1'),
 ('5','have_personal_category','','','','1'),
 ('6','have_personal_category','','','','1'),
 ('7','have_personal_category','','','','1'),
 ('8','have_personal_category','','','','1'),
 ('9','have_personal_category','','','','1'),
 ('10','have_personal_category','','','','1'),
 ('1','vote_in_polls','','','','1'),
 ('2','vote_in_polls','','','','1'),
 ('3','vote_in_polls','','','','1'),
 ('4','vote_in_polls','','','','1'),
 ('5','vote_in_polls','','','','1'),
 ('6','vote_in_polls','','','','1'),
 ('7','vote_in_polls','','','','1'),
 ('8','vote_in_polls','','','','1'),
 ('9','vote_in_polls','','','','1'),
 ('10','vote_in_polls','','','','1'),
 ('2','use_very_dangerous_comcode','','','','1'),
 ('3','use_very_dangerous_comcode','','','','1'),
 ('2','open_virtual_roots','','','','1'),
 ('3','open_virtual_roots','','','','1'),
 ('2','scheduled_publication_times','','','','1'),
 ('3','scheduled_publication_times','','','','1'),
 ('2','mass_delete_from_ip','','','','1'),
 ('3','mass_delete_from_ip','','','','1'),
 ('2','exceed_filesize_limit','','','','1'),
 ('3','exceed_filesize_limit','','','','1'),
 ('2','view_revision_history','','','','1'),
 ('3','view_revision_history','','','','1'),
 ('2','sees_javascript_error_alerts','','','','1'),
 ('3','sees_javascript_error_alerts','','','','1'),
 ('2','see_software_docs','','','','1'),
 ('3','see_software_docs','','','','1'),
 ('2','bypass_flood_control','','','','1'),
 ('3','bypass_flood_control','','','','1'),
 ('2','allow_html','','','','1'),
 ('3','allow_html','','','','1'),
 ('2','remove_page_split','','','','1'),
 ('3','remove_page_split','','','','1'),
 ('2','access_closed_site','','','','1'),
 ('3','access_closed_site','','','','1'),
 ('2','bypass_bandwidth_restriction','','','','1'),
 ('3','bypass_bandwidth_restriction','','','','1'),
 ('2','comcode_dangerous','','','','1'),
 ('3','comcode_dangerous','','','','1'),
 ('2','comcode_nuisance','','','','1'),
 ('3','comcode_nuisance','','','','1'),
 ('2','see_php_errors','','','','1'),
 ('3','see_php_errors','','','','1'),
 ('2','see_stack_dump','','','','1'),
 ('3','see_stack_dump','','','','1'),
 ('2','bypass_word_filter','','','','1'),
 ('3','bypass_word_filter','','','','1'),
 ('2','view_profiling_modes','','','','1'),
 ('3','view_profiling_modes','','','','1'),
 ('2','access_overrun_site','','','','1'),
 ('3','access_overrun_site','','','','1'),
 ('2','bypass_validation_highrange_content','','','','1'),
 ('3','bypass_validation_highrange_content','','','','1'),
 ('2','bypass_validation_midrange_content','','','','1'),
 ('3','bypass_validation_midrange_content','','','','1'),
 ('2','edit_highrange_content','','','','1'),
 ('3','edit_highrange_content','','','','1'),
 ('2','edit_midrange_content','','','','1'),
 ('3','edit_midrange_content','','','','1'),
 ('2','edit_lowrange_content','','','','1'),
 ('3','edit_lowrange_content','','','','1'),
 ('2','edit_own_highrange_content','','','','1'),
 ('3','edit_own_highrange_content','','','','1'),
 ('2','edit_own_midrange_content','','','','1'),
 ('3','edit_own_midrange_content','','','','1'),
 ('2','delete_highrange_content','','','','1'),
 ('3','delete_highrange_content','','','','1'),
 ('2','delete_midrange_content','','','','1'),
 ('3','delete_midrange_content','','','','1'),
 ('2','delete_lowrange_content','','','','1'),
 ('3','delete_lowrange_content','','','','1'),
 ('2','delete_own_highrange_content','','','','1'),
 ('3','delete_own_highrange_content','','','','1'),
 ('2','delete_own_midrange_content','','','','1'),
 ('3','delete_own_midrange_content','','','','1'),
 ('2','delete_own_lowrange_content','','','','1'),
 ('3','delete_own_lowrange_content','','','','1'),
 ('2','can_submit_to_others_categories','','','','1'),
 ('3','can_submit_to_others_categories','','','','1'),
 ('2','search_engine_links','','','','1'),
 ('3','search_engine_links','','','','1'),
 ('2','view_content_history','','','','1'),
 ('3','view_content_history','','','','1'),
 ('2','restore_content_history','','','','1'),
 ('3','restore_content_history','','','','1'),
 ('2','delete_content_history','','','','1'),
 ('3','delete_content_history','','','','1'),
 ('2','submit_cat_highrange_content','','','','1'),
 ('3','submit_cat_highrange_content','','','','1'),
 ('2','submit_cat_midrange_content','','','','1'),
 ('3','submit_cat_midrange_content','','','','1'),
 ('2','submit_cat_lowrange_content','','','','1'),
 ('3','submit_cat_lowrange_content','','','','1'),
 ('2','edit_cat_highrange_content','','','','1'),
 ('3','edit_cat_highrange_content','','','','1'),
 ('2','edit_cat_midrange_content','','','','1'),
 ('3','edit_cat_midrange_content','','','','1'),
 ('2','edit_cat_lowrange_content','','','','1'),
 ('3','edit_cat_lowrange_content','','','','1'),
 ('2','delete_cat_highrange_content','','','','1'),
 ('3','delete_cat_highrange_content','','','','1'),
 ('2','delete_cat_midrange_content','','','','1'),
 ('3','delete_cat_midrange_content','','','','1'),
 ('2','delete_cat_lowrange_content','','','','1'),
 ('3','delete_cat_lowrange_content','','','','1'),
 ('2','edit_own_cat_highrange_content','','','','1'),
 ('3','edit_own_cat_highrange_content','','','','1'),
 ('2','edit_own_cat_midrange_content','','','','1'),
 ('3','edit_own_cat_midrange_content','','','','1'),
 ('2','edit_own_cat_lowrange_content','','','','1'),
 ('3','edit_own_cat_lowrange_content','','','','1'),
 ('2','delete_own_cat_highrange_content','','','','1'),
 ('3','delete_own_cat_highrange_content','','','','1'),
 ('2','delete_own_cat_midrange_content','','','','1'),
 ('3','delete_own_cat_midrange_content','','','','1'),
 ('2','delete_own_cat_lowrange_content','','','','1'),
 ('3','delete_own_cat_lowrange_content','','','','1'),
 ('2','mass_import','','','','1'),
 ('3','mass_import','','','','1'),
 ('3','bypass_validation_lowrange_content','','forums','8','1'),
 ('3','bypass_validation_midrange_content','','forums','8','1'),
 ('2','full_banner_setup','','','','1'),
 ('3','full_banner_setup','','','','1'),
 ('2','view_anyones_banner_stats','','','','1'),
 ('3','view_anyones_banner_stats','','','','1'),
 ('2','banner_free','','','','1'),
 ('3','banner_free','','','','1'),
 ('1','view_calendar','','','','1'),
 ('2','view_calendar','','','','1'),
 ('3','view_calendar','','','','1'),
 ('4','view_calendar','','','','1'),
 ('5','view_calendar','','','','1'),
 ('6','view_calendar','','','','1'),
 ('7','view_calendar','','','','1'),
 ('8','view_calendar','','','','1'),
 ('9','view_calendar','','','','1'),
 ('10','view_calendar','','','','1'),
 ('1','add_public_events','','','','1'),
 ('2','add_public_events','','','','1'),
 ('3','add_public_events','','','','1'),
 ('4','add_public_events','','','','1'),
 ('5','add_public_events','','','','1'),
 ('6','add_public_events','','','','1'),
 ('7','add_public_events','','','','1'),
 ('8','add_public_events','','','','1'),
 ('9','add_public_events','','','','1'),
 ('10','add_public_events','','','','1'),
 ('2','sense_personal_conflicts','','','','1'),
 ('3','sense_personal_conflicts','','','','1'),
 ('2','view_event_subscriptions','','','','1'),
 ('3','view_event_subscriptions','','','','1'),
 ('2','high_catalogue_entry_timeout','','','','1'),
 ('3','high_catalogue_entry_timeout','','','','1'),
 ('2','seedy_manage_tree','','','','1'),
 ('3','seedy_manage_tree','','','','1'),
 ('1','create_private_room','','','','1'),
 ('2','create_private_room','','','','1'),
 ('3','create_private_room','','','','1'),
 ('4','create_private_room','','','','1'),
 ('5','create_private_room','','','','1'),
 ('6','create_private_room','','','','1'),
 ('7','create_private_room','','','','1'),
 ('8','create_private_room','','','','1'),
 ('9','create_private_room','','','','1'),
 ('10','create_private_room','','','','1'),
 ('1','start_im','','','','1'),
 ('2','start_im','','','','1'),
 ('3','start_im','','','','1'),
 ('4','start_im','','','','1'),
 ('5','start_im','','','','1'),
 ('6','start_im','','','','1'),
 ('7','start_im','','','','1'),
 ('8','start_im','','','','1'),
 ('9','start_im','','','','1'),
 ('10','start_im','','','','1'),
 ('1','moderate_my_private_rooms','','','','1'),
 ('2','moderate_my_private_rooms','','','','1'),
 ('3','moderate_my_private_rooms','','','','1'),
 ('4','moderate_my_private_rooms','','','','1'),
 ('5','moderate_my_private_rooms','','','','1'),
 ('6','moderate_my_private_rooms','','','','1'),
 ('7','moderate_my_private_rooms','','','','1'),
 ('8','moderate_my_private_rooms','','','','1'),
 ('9','moderate_my_private_rooms','','','','1'),
 ('10','moderate_my_private_rooms','','','','1'),
 ('2','ban_chatters_from_rooms','','','','1'),
 ('3','ban_chatters_from_rooms','','','','1'),
 ('2','may_download_gallery','','','','1'),
 ('3','may_download_gallery','','','','1'),
 ('2','high_personal_gallery_limit','','','','1'),
 ('3','high_personal_gallery_limit','','','','1'),
 ('2','no_personal_gallery_limit','','','','1'),
 ('3','no_personal_gallery_limit','','','','1'),
 ('2','choose_iotd','','','','1'),
 ('3','choose_iotd','','','','1'),
 ('2','change_newsletter_subscriptions','','','','1'),
 ('3','change_newsletter_subscriptions','','','','1'),
 ('1','use_points','','','','1'),
 ('2','use_points','','','','1'),
 ('3','use_points','','','','1'),
 ('4','use_points','','','','1'),
 ('5','use_points','','','','1'),
 ('6','use_points','','','','1'),
 ('7','use_points','','','','1'),
 ('8','use_points','','','','1'),
 ('9','use_points','','','','1'),
 ('10','use_points','','','','1'),
 ('2','give_points_self','','','','1'),
 ('3','give_points_self','','','','1'),
 ('2','have_negative_gift_points','','','','1'),
 ('3','have_negative_gift_points','','','','1'),
 ('2','give_negative_points','','','','1'),
 ('3','give_negative_points','','','','1'),
 ('2','view_charge_log','','','','1'),
 ('3','view_charge_log','','','','1'),
 ('2','trace_anonymous_gifts','','','','1'),
 ('3','trace_anonymous_gifts','','','','1'),
 ('2','choose_poll','','','','1'),
 ('3','choose_poll','','','','1'),
 ('2','access_ecommerce_in_test_mode','','','','1'),
 ('3','access_ecommerce_in_test_mode','','','','1'),
 ('2','bypass_quiz_repeat_time_restriction','','','','1'),
 ('3','bypass_quiz_repeat_time_restriction','','','','1'),
 ('2','perform_tests','','','','1'),
 ('3','perform_tests','','','','1'),
 ('1','add_tests','','','','1'),
 ('2','add_tests','','','','1'),
 ('3','add_tests','','','','1'),
 ('4','add_tests','','','','1'),
 ('5','add_tests','','','','1'),
 ('6','add_tests','','','','1'),
 ('7','add_tests','','','','1'),
 ('8','add_tests','','','','1'),
 ('9','add_tests','','','','1'),
 ('10','add_tests','','','','1'),
 ('1','edit_own_tests','','','','1'),
 ('2','edit_own_tests','','','','1'),
 ('3','edit_own_tests','','','','1'),
 ('4','edit_own_tests','','','','1'),
 ('5','edit_own_tests','','','','1'),
 ('6','edit_own_tests','','','','1'),
 ('7','edit_own_tests','','','','1'),
 ('8','edit_own_tests','','','','1'),
 ('9','edit_own_tests','','','','1'),
 ('10','edit_own_tests','','','','1'),
 ('2','support_operator','','','','1'),
 ('3','support_operator','','','','1'),
 ('2','view_others_tickets','','','','1'),
 ('3','view_others_tickets','','','','1'),
 ('2','upload_anything_filedump','','','','1'),
 ('3','upload_anything_filedump','','','','1'),
 ('1','upload_filedump','','','','1'),
 ('2','upload_filedump','','','','1'),
 ('3','upload_filedump','','','','1'),
 ('4','upload_filedump','','','','1'),
 ('5','upload_filedump','','','','1'),
 ('6','upload_filedump','','','','1'),
 ('7','upload_filedump','','','','1'),
 ('8','upload_filedump','','','','1'),
 ('9','upload_filedump','','','','1'),
 ('10','upload_filedump','','','','1'),
 ('2','delete_anything_filedump','','','','1'),
 ('3','delete_anything_filedump','','','','1');

