<?php /*

 ocPortal
 Copyright (c) ocProducts, 2004-2014

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license		http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright	ocProducts Ltd
 * @package		comcode_flip_tag
 */

class Hook_addon_registry_comcode_flip_tag
{
	/**
	 * Get a list of file permissions to set
	 *
	 * @return array			File permissions to set
	 */
	function get_chmod_array()
	{
		return array();
	}

	/**
	 * Get the version of ocPortal this addon is for
	 *
	 * @return float			Version number
	 */
	function get_version()
	{
		return ocp_version_number();
	}

	/**
	 * Get the addon category
	 *
	 * @return string			The category
	 */
	function get_category()
	{
		return 'Graphical';
	}

	/**
	 * Get the addon author
	 *
	 * @return string			The author
	 */
	function get_author()
	{
		return 'Chris Graham';
	}

	/**
	 * Find other authors
	 *
	 * @return array			A list of co-authors that should be attributed
	 */
	function get_copyright_attribution()
	{
		return array(
			'Luca Manno',
		);
	}

	/**
	 * Get the addon licence (one-line summary only)
	 *
	 * @return string			The licence
	 */
	function get_licence()
	{
		return 'Based on open code posted without a license';
	}

	/**
	 * Get the description of the addon
	 *
	 * @return string			Description of the addon
	 */
	function get_description()
	{
		return 'Create a tiled text-flipping effect.

[code=\"Comcode\"][flip=\"A\" final_color=\"FF0000\" speed=\"400\"]B[/flip][/code]

The above example creates a flip between text A and text B, taking 400ms. This is designed to use short messages or one word answers. If you want to change any of the standard CSS for this addon you can edit the flip.css file. Note: flip uses jQuery for the flip effect, so this example bundles jQuery and shows how it can be used.';
	}

	/**
	 * Get a list of tutorials that apply to this addon
	 *
	 * @return array			List of tutorials
	 */
	function get_applicable_tutorials()
	{
		return array(
		);
	}

	/**
	 * Get a mapping of dependency types
	 *
	 * @return array			File permissions to set
	 */
	function get_dependencies()
	{
		return array(
			'requires'=>array(
				'Javascript enabled',
			),
			'recommends'=>array(
			),
			'conflicts_with'=>array(
			)
		);
	}

	/**
	 * Get a list of files that belong to this addon
	 *
	 * @return array			List of files
	 */
	function get_file_list()
	{
		return array(
			'sources_custom/hooks/systems/addon_registry/comcode_flip_tag.php',
			'themes/default/css_custom/flip.css',
			'themes/default/templates_custom/COMCODE_FLIP.tpl',
			'themes/default/templates_custom/JAVASCRIPT_JQUERY.tpl',
			'themes/default/templates_custom/JAVASCRIPT_JQUERY_EFFECTS_CORE.tpl',
			'themes/default/templates_custom/JAVASCRIPT_JQUERY_FLIP.tpl',
			'themes/default/templates_custom/JAVASCRIPT_JQUERY_UI_CORE.tpl',
			'sources_custom/hooks/systems/comcode/flip.php',
		);
	}
}