<?php /*

 ocPortal
 Copyright (c) ocProducts, 2004-2014

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license		http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright	ocProducts Ltd
 * @package		referrals
 */

class Hook_addon_registry_referrals
{
	/**
	 * Get a list of file permissions to set
	 *
	 * @return array			File permissions to set
	 */
	function get_chmod_array()
	{
		return array();
	}

	/**
	 * Get the version of ocPortal this addon is for
	 *
	 * @return float			Version number
	 */
	function get_version()
	{
		return ocp_version_number();
	}

	/**
	 * Get the addon category
	 *
	 * @return string			The category
	 */
	function get_category()
	{
		return 'New Features';
	}

	/**
	 * Get the addon author
	 *
	 * @return string			The author
	 */
	function get_author()
	{
		return 'Chris Graham';
	}

	/**
	 * Find other authors
	 *
	 * @return array			A list of co-authors that should be attributed
	 */
	function get_copyright_attribution()
	{
		return array(
			'Icon by Titan Creations',
		);
	}

	/**
	 * Get the addon licence (one-line summary only)
	 *
	 * @return string			The licence
	 */
	function get_licence()
	{
		return 'Licensed on the same terms as ocPortal';
	}

	/**
	 * Get the description of the addon
	 *
	 * @return string			Description of the addon
	 */
	function get_description()
	{
		return 'A referrals package.

Allows people to specify who referred them when they join your site or other configurable triggers in the system, and defines award levels people can reach. Note that tracking of referrals and award of point is a default part of ocPortal, but referrals are only picked up if made via the recommend module and the new member uses the same address they were recommended to. This addon will allow referrals to be specified explicitly via the URL or typed in manually.

1) Edit the settings in text_custom/referrals.txt (there is an editing link for this on the setup menu)

2) Edit the messages in the referrals.ini language file as required.

3) Probably set up a page on your site explaining the awards you give.';
	}

	/**
	 * Get a list of tutorials that apply to this addon
	 *
	 * @return array			List of tutorials
	 */
	function get_applicable_tutorials()
	{
		return array(
		);
	}

	/**
	 * Get a mapping of dependency types
	 *
	 * @return array			File permissions to set
	 */
	function get_dependencies()
	{
		return array(
			'requires'=>array(
			),
			'recommends'=>array(
			),
			'conflicts_with'=>array(
			)
		);
	}

	/**
	 * Get a list of files that belong to this addon
	 *
	 * @return array			List of files
	 */
	function get_file_list()
	{
		return array(
			'sources_custom/hooks/systems/addon_registry/referrals.php',
			'sources_custom/hooks/systems/referrals/.htaccess',
			'sources_custom/hooks/systems/notifications/referral.php',
			'sources_custom/hooks/systems/notifications/referral_staff.php',
			'text_custom/referrals.txt',
			'data_custom/referrer_report.php',
			'lang_custom/EN/referrals.ini',
			'sources_custom/ocf_join.php',
			'sources_custom/referrals.php',
			'sources_custom/hooks/systems/ecommerce/usergroup.php',
			'sources_custom/hooks/systems/ecommerce/cart_orders.php',
			'sources_custom/hooks/systems/referrals/index.html',
			'sources_custom/hooks/systems/do_next_menus/referrals.php',
			'sources_custom/hooks/modules/members/referrals.php',
			'themes/default/images_custom/bigicons/referrals.png',
			'adminzone/pages/comcode_custom/EN/referrals.txt',
			'data_custom/referrals_install.php',
			'data_custom/referrals_uninstall.php',
			'adminzone/pages/modules_custom/admin_referrals.php',
			'sources_custom/hooks/systems/startup/referrals.php',
		);
	}
}