<?php /*

 ocPortal
 Copyright (c) ocProducts, 2004-2012

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license		http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright	ocProducts Ltd
 * @package		ldap
 */


class Hook_do_next_menus_ldap
{

	/**
	 * Standard modular run function for do_next_menu hooks. They find links to put on standard navigation menus of the system.
	 *
	 * @return array			Array of links and where to show
	 */
	function run()
	{
		if (!addon_installed('ldap')) return array();

		return array(
			(get_forum_type()!='ocf')?NULL:array('security','ldap',array('admin_ocf_ldap',array('type'=>'misc'),get_module_zone('admin_ocf_ldap')),do_lang_tempcode('LDAP'),('DOC_LDAP')),
		);
	}

}


