<?php /*

 ocPortal
 Copyright (c) ocProducts, 2004-2013

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license		http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright	ocProducts Ltd
 * @package		chat
 */

require_code('content_fs');

class Hook_occle_fs_chat extends content_fs_base
{
	var $file_content_type='chat';

	/**
	 * Standard modular add function for content hooks. Adds some content with the given title and properties.
	 *
	 * @param  SHORT_TEXT	Content title
	 * @param  ID_TEXT		Parent category (blank: root / not applicable)
	 * @param  array			Properties (may be empty, properties given are open to interpretation by the hook but generally correspond to database fields)
	 * @return ID_TEXT		The content ID
	 */
	function _file_add($title,$category,$properties)
	{
		require_code('chat2');

		$welcome=$this->_default_property_str($properties,'welcome');
		$room_owner=$this->_default_property_int_null($properties,'room_owner');
		$allow2=$this->_default_property_str($properties,'allow2');
		$allow2_groups=$this->_default_property_str($properties,'allow2_groups');
		$disallow2=$this->_default_property_str($properties,'disallow2');
		$disallow2_groups=$this->_default_property_str($properties,'disallow2_groups');
		$roomlang=$this->_default_property_str($properties,'roomlang');
		if ($roomlang=='') $roomlang=get_site_default_lang();
		$is_im=$this->_default_property_int($properties,'is_im');

		$id=add_chatroom($welcome,$title,$room_owner,$allow2,$allow2_groups,$disallow2,$disallow2_groups,$roomlang,$is_im);
		return strval($id);
	}

	/**
	 * Standard modular delete function for content hooks. Deletes the content.
	 *
	 * @param  ID_TEXT	The content ID
	 */
	function _file_delete($content_id)
	{
		require_code('chat2');
		delete_chatroom(intval($content_id));
	}
}
