<?php /*

 ocPortal
 Copyright (c) ocProducts, 2004-2013

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license		http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright	ocProducts Ltd
 * @package		ocf_forum
 */

require_code('content_fs');

class Hook_occle_fs_forums extends content_fs_base
{
	var $folder_content_type=array('forum','topic');
	var $file_content_type='post';

	/**
	 * Whether the filesystem hook is active.
	 *
	 * @return boolean		Whether it is
	 */
	function _is_active()
	{
		return (get_forum_type()=='ocf');
	}

	/**
	 * Find whether a kind of content handled by this hook (folder or file) can be under a particular kind of folder.
	 *
	 * @param  ID_TEXT		Folder content type
	 * @param  ID_TEXT		Content type (may be file or folder)
	 * @return boolean		Whether it can
	 */
	function _has_parent_child_relationship($above,$under)
	{
		switch ($above)
		{
			case 'forum':
				return ($under=='forum') || ($under=='topic');
			case 'topic':
				return ($under=='post');
		}
		return false;
	}

	/**
	 * Standard modular introspection function.
	 *
	 * @param  ID_TEXT		Parent category (blank: root / not applicable)
	 * @return array			The properties available for the content type
	 */
	function _enumerate_folder_properties($category)
	{
		if (substr($category,0,6)=='FORUM-')
		{
			return array(
				'description'=>'LONG_TRANS',
				'forum_grouping_id'=>'forum_grouping',
				'position'=>'INTEGER',
				'post_count_increment'=>'BINARY',
				'order_sub_alpha'=>'BINARY',
				'intro_question'=>'LONG_TRANS',
				'intro_answer'=>'LONG_TRANS',
				'redirection'=>'SHORT_TEXT|forum',
				'order'=>'ID_TEXT',
				'is_threaded'=>'BINARY',
			);
		}

		return array(
			'emoticon'=>'SHORT_TEXT',
			'validated'=>'BINARY',
			'open'=>'BINARY',
			'pinned'=>'BINARY',
			'sunk'=>'BINARY',
			'cascading'=>'BINARY',
			'pt_from'=>'?member',
			'pt_to'=>'?member',
			'num_views'=>'INTEGER',
			'description_link'=>'SHORT_TEXT',
			'poll'=>'LONG_TRANS',
		);
	}

	/**
	 * Standard modular date fetch function for content hooks. Defined when getting an edit date is not easy.
	 *
	 * @param  array			Content row (not full, but does contain the ID)
	 * @param  ID_TEXT		Parent category (blank: root / not applicable)
	 * @return ?TIME			The edit date or add date, whichever is higher (NULL: could not find one)
	 */
	function _get_folder_edit_date($row,$category)
	{
		if (substr($category,0,6)=='FORUM-')
		{
			$query='SELECT MAX(date_and_time) FROM '.get_table_prefix().'adminlogs WHERE '.db_string_equal_to('param_a',strval($row['id'])).' AND  ('.db_string_equal_to('the_type','ADD_FORUM').' OR '.db_string_equal_to('the_type','EDIT_FORUM').')';
			return $GLOBALS['SITE_DB']->query_value_if_there($query);
		}

		return NULL; // Will be picked up naturally from t_cache_first_time/t_cache_last_time
	}

	/**
	 * Get the filename for a content ID. Note that filenames are unique across all folders in a filesystem.
	 *
	 * @param  ID_TEXT	The content type
	 * @param  ID_TEXT	The content ID
	 * @return ID_TEXT	The filename
	 */
	function _folder_convert_id_to_filename($content_type,$content_id)
	{
		if ($content_type=='forum')
			return 'FORUM-'.parent::_folder_convert_id_to_filename($content_type,$content_id,'forum');

		return parent::_folder_convert_id_to_filename($content_type,$content_id);
	}

	/**
	 * Get the content ID for a filename. Note that filenames are unique across all folders in a filesystem.
	 *
	 * @param  ID_TEXT	The filename, or filepath
	 * @return array		A pair: The content type, the content ID
	 */
	function _folder_convert_filename_to_id($filename)
	{
		if (substr($filename,0,6)=='FORUM-')
			return parent::_folder_convert_filename_to_id(substr($filename,6),'forum');

		return parent::_folder_convert_filename_to_id($filename,'topic');
	}

	/**
	 * Standard modular add function for content hooks. Adds some content with the given label and properties.
	 *
	 * @param  SHORT_TEXT	Filename OR Content label
	 * @param  string			The path (blank: root / not applicable)
	 * @param  array			Properties (may be empty, properties given are open to interpretation by the hook but generally correspond to database fields)
	 * @return ~ID_TEXT		The content ID (false: error)
	 */
	function _folder_add($filename,$path,$properties)
	{
		list($category_content_type,$category)=$this->_folder_convert_filename_to_id($path);

		list($properties,$label)=$this->_folder_magic_filter($filename,$path,$properties);

		if ($category_content_type=='forum')
		{
			if ($category_content_type!='forum') return false;
			if ($category=='') return false; // Can't create more than one root

			require_code('ocf_forums_action');

			$description=$this->_default_property_str($properties,'description');
			$forum_grouping_id=/*if grouping resource type was not here we could cheat with $GLOBALS['FORUM_DB']->query_select_value('f_forum_groupings','MIN(id)');*/$this->_default_property_str($properties,'forum_grouping_id');
			$access_mapping=array();
			$parent_forum=$this->_integer_category($category);
			$position=$this->_default_property_str($properties,'position');
			$post_count_increment=$this->_default_property_str($properties,'post_count_increment');
			$order_sub_alpha=$this->_default_property_str($properties,'order_sub_alpha');
			$intro_question=$this->_default_property_str($properties,'intro_question');
			$intro_answer=$this->_default_property_str($properties,'intro_answer');
			$redirection=$this->_default_property_str($properties,'redirection');
			$order=$this->_default_property_str($properties,'order');
			$is_threaded=$this->_default_property_str($properties,'is_threaded');
			$id=ocf_make_forum($label,$description,$forum_grouping_id,$access_mapping,$parent_forum,$position,$post_count_increment,$order_sub_alpha,$intro_question,$intro_answer,$redirection,$order,$is_threaded);
		} else
		{
			if ($category_content_type!='forum') return false;
			if ($category=='') return false;

			require_code('ocf_topics_action');

			$forum_id=$this->_integer_category($category);
			$emoticon=$this->_default_property_str($properties,'emoticon');
			$validated=$this->_default_property_str($properties,'validated');
			$open=$this->_default_property_str($properties,'open');
			$pinned=$this->_default_property_str($properties,'pinned');
			$sunk=$this->_default_property_str($properties,'sunk');
			$cascading=$this->_default_property_str($properties,'cascading');
			$pt_from=$this->_default_property_str($properties,'pt_from');
			$pt_to=$this->_default_property_str($properties,'pt_to');
			$num_views=$this->_default_property_str($properties,'num_views');
			$description_link=$this->_default_property_str($properties,'description_link');
			$id=ocf_make_topic($forum_id,$label,$emoticon,$validated,$open,$pinned,$sunk,$cascading,$pt_from,$pt_to,false,$num_views,NULL,$description_link);

			if ((array_key_exists('poll',$properties)) && ($properties['poll']!=''))
			{
				require_code('ocf_polls_action');

				$poll_data=unserialize($properties['poll']);

				$question=$poll_data['question'];
				$is_private=$poll_data['is_private'];
				$is_open=$poll_data['is_open'];
				$minimum_selections=$poll_data['minimum_selections'];
				$maximum_selections=$poll_data['maximum_selections'];
				$requires_reply=$poll_data['requires_reply'];
				$answers=$poll_data['answers']; // A list of pairs of the potential voteable answers and the number of votes.

				ocf_make_poll($id,$question,$is_private,$is_open,$minimum_selections,$maximum_selections,$requires_reply,$answers,false);
			}
		}

		return strval($id);
	}

	/**
	 * Standard modular delete function for content hooks. Deletes the content.
	 *
	 * @param  ID_TEXT	The filename
	 */
	function _folder_delete($filename)
	{
		list($content_type,$content_id)=$this->_folder_convert_filename_to_id($filename);

		if ($content_type=='forum')
		{
			require_code('ocf_forums_action2');
			ocf_delete_forum(intval($content_id));
		} else
		{
			require_code('ocf_topics_action2');
			ocf_delete_topic(intval($content_id));
		}
	}

	/**
	 * Standard modular introspection function.
	 *
	 * @return array			The properties available for the content type
	 */
	function _enumerate_file_properties()
	{
		return array(
			'post'=>'LONG_TRANS',
			'skip_sig'=>'BINARY',
			'validated'=>'BINARY',
			'is_emphasised'=>'BINARY',
			'poster_name_if_guest'=>'ID_TEXT',
			'ip_address'=>'IP',
			'intended_solely_for'=>'?member',
			'sunk'=>'BINARY',
			'anonymous'=>'BINARY',
			'parent_id'=>'?post',
			'poster'=>'member',
			'last_edit_by'=>'?member',
			'add_date'=>'TIME',
			'edit_date'=>'?TIME',
		);
	}

	/**
	 * Standard modular add function for content hooks. Adds some content with the given label and properties.
	 *
	 * @param  SHORT_TEXT	Filename OR Content label
	 * @param  string			The path (blank: root / not applicable)
	 * @param  array			Properties (may be empty, properties given are open to interpretation by the hook but generally correspond to database fields)
	 * @return ~ID_TEXT		The content ID (false: error, could not create via these properties / here)
	 */
	function _file_add($filename,$path,$properties)
	{
		list($category_content_type,$category)=$this->_folder_convert_filename_to_id($path);
		list($properties,$label)=$this->_file_magic_filter($filename,$path,$properties);

		if ($category=='') return false;
		if ($category_content_type!='topic') return false;

		require_code('ocf_posts_action');

		$topic_id=$this->_integer_category($category);
		$post=$this->_default_property_str($properties,'post');
		$skip_sig=$this->_default_property_int($properties,'skip_sig');
		$validated=$this->_default_property_int_null($properties,'validated');
		if (is_null($validated)) $validated=1;
		$is_emphasised=$this->_default_property_int($properties,'is_emphasised');
		$poster_name_if_guest=$this->_default_property_str($properties,'poster_name_if_guest');
		$ip_address=$this->_default_property_str_null($properties,'ip_address');
		$time=$this->_default_property_int_null($properties,'add_date');
		$poster=$this->_default_property_int_null($properties,'poster');
		$intended_solely_for=$this->_default_property_int_null($properties,'intended_solely_for');
		$last_edit_time=$this->_default_property_int_null($properties,'edit_date');
		$last_edit_by=$this->_default_property_int_null($properties,'last_edit_by');
		$sunk=$this->_default_property_int($properties,'sunk');
		$anonymous=$this->_default_property_int($properties,'anonymous');
		$parent_id=$this->_default_property_int_null($properties,'parent_id');
		$id=ocf_make_post($topic_id,$label,$post,$skip_sig,NULL,$validated,$is_emphasised,$poster_name_if_guest,$ip_address,$time,$poster,$intended_solely_for,$last_edit_time,$last_edit_by,false,true,NULL,false,NULL,$sunk,NULL,$anonymous,true,NULL,false,$parent_id);
		return strval($id);
	}

	/**
	 * Standard modular delete function for content hooks. Deletes the content.
	 *
	 * @param  ID_TEXT	The filename
	 */
	function _file_delete($filename)
	{
		list($content_type,$content_id)=$this->_file_convert_filename_to_id($filename);

		require_code('ocf_posts_action2');
		ocf_delete_post(intval($content_id));
	}
}
