<a rel="enclosure" target="_blank" title="{!DOWNLOAD_ATTACHMENT_REMOTE,{A_ORIGINAL_FILENAME*},{$ATTACHMENT_DOWNLOADS*,{ID}}}: {!LINK_NEW_WINDOW}" href="{A_URL*}">{+START,IF_NON_PASSED,WYSIWYG_SAFE}{!DOWNLOAD_ATTACHMENT_REMOTE,{A_ORIGINAL_FILENAME*},{$ATTACHMENT_DOWNLOADS*,{ID}}}{+END}{+START,IF_PASSED,WYSIWYG_SAFE}{A_ORIGINAL_FILENAME*}{+END}</a>

{+START,IF_NON_EMPTY,{A_DESCRIPTION}}
	<p class="associated_caption">
		{A_DESCRIPTION}
	</p>
{+END}

