{+START,BOX,{!NEWSLETTER}{$?,{$NEQ,{NEWSLETTER_TITLE},{!GENERAL}},: {NEWSLETTER_TITLE*}},,{$?,{$GET,in_panel},panel,classic}}
	{$?,{PATH_EXISTS},{!SUCCESS_NEWSLETTER_AUTO_INSTANT,{PASSWORD*}},{!SUCCESS_NEWSLETTER_AUTO,{PASSWORD*}}}
{+END}
