{+START,IF_ARRAY_NON_EMPTY,MISSING_LANG_STRINGS}
	{+START,BOX,{!MISSING_LANG_STRINGS}}<p>
		{+IMPLODE,&#044; ,MISSING_LANG_STRINGS}
	</p>{+END}
{+END}

{+START,IF_ARRAY_NON_EMPTY,FUSED_LANG_STRINGS}
	<br />
	{+START,BOX,{!FUSED_LANG_STRINGS}}<p>
		{+IMPLODE,<br /><br />,FUSED_LANG_STRINGS,1}
	</p>{+END}
{+END}

{+START,IF_ARRAY_NON_EMPTY,ORPHANED_LANG_STRINGS}
	<br />
	{+START,BOX,{!ORPHANED_LANG_STRINGS}}<p>
		{+IMPLODE,&#044; ,ORPHANED_LANG_STRINGS}
	</p>{+END}
{+END}

