{+START,IF_NON_PASSED_OR_FALSE,WYSIWYG_SAFE}
	{+START,IF_EMPTY,{$META_DATA,image}}
		{$META_DATA,image,{THUMB_URL}}
	{+END}
{+END}

{+START,IF_PASSED_AND_TRUE,FRAMED}
	<figure class="attachment">
		<figcaption>{!IMAGE}</figcaption>
		<div>
			{$PARAGRAPH,{DESCRIPTION}}

			<div class="attachment_details">
				<a {+START,IF,{$NOT,{$INLINE_STATS}}}onclick="return ga_track(this,'{!IMAGE;*}','{FILENAME;*}');" {+END} target="_blank" title="{+START,IF_NON_EMPTY,{DESCRIPTION}}{DESCRIPTION*}: {+END}{!LINK_NEW_WINDOW}" {+START,IF_PASSED,CLICK_URL}href="{CLICK_URL*}"{+END}{+START,IF_NON_PASSED,CLICK_URL}rel="lightbox" href="{URL*}"{+END}><img {+START,IF,{$NEQ,{WIDTH}x{HEIGHT},{$CONFIG_OPTION,thumb_width}x{$CONFIG_OPTION,thumb_width}}}width="{WIDTH*}" height="{HEIGHT*}" {+END}src="{THUMB_URL*}"{+START,IF_NON_PASSED_OR_FALSE,WYSIWYG_SAFE}{+START,IF,{EXPANDABLE}}{+START,IF_PASSED,NUM_DOWNLOADS} alt="{!IMAGE_ATTACHMENT,{NUM_DOWNLOADS*},{CLEAN_FILESIZE*}}"{+END}{+END}{+START,IF,{$NOT,{EXPANDABLE}}} title="{DESCRIPTION*}" alt="{DESCRIPTION*}"{+END}{+END}{+START,IF_PASSED_AND_TRUE,WYSIWYG_SAFE}{+START,IF,{EXPANDABLE}}{+END}{+START,IF,{$NOT,{EXPANDABLE}}} title="{DESCRIPTION*}"{+END} alt="{DESCRIPTION*}"{+END} /></a>

				{$,Uncomment for a download link \{+START,INCLUDE,MEDIA__DOWNLOAD_LINK\}\{+END\}}
			</div>
		</div>
	</figure>
{+END}
{+START,IF_NON_PASSED_OR_FALSE,FRAMED}
	{+START,IF,{EXPANDABLE}}<a {+START,IF_PASSED,CLICK_URL}href="{CLICK_URL*}"{+END}{+START,IF_NON_PASSED,CLICK_URL}rel="lightbox" href="{URL*}"{+END} target="_blank" title="{DESCRIPTION*} {!LINK_NEW_WINDOW}">{+END}<img class="attachment_img"{+START,IF_NON_EMPTY,{WIDTH}} width="{WIDTH*}"{+END}{+START,IF_NON_EMPTY,{HEIGHT}} height="{HEIGHT*}"{+END} src="{THUMB_URL*}"{+START,IF_NON_PASSED_OR_FALSE,WYSIWYG_SAFE}{+START,IF,{EXPANDABLE}}{+START,IF_PASSED,NUM_DOWNLOADS} alt="{!IMAGE_ATTACHMENT,{NUM_DOWNLOADS*},{CLEAN_FILESIZE*}}"{+END}{+END}{+START,IF,{$NOT,{EXPANDABLE}}} title="{DESCRIPTION*}" alt="{DESCRIPTION*}"{+END}{+END}{+START,IF_PASSED_AND_TRUE,WYSIWYG_SAFE}{+START,IF,{EXPANDABLE}}{+END}{+START,IF,{$NOT,{EXPANDABLE}}} title="{DESCRIPTION*}"{+END} alt="{DESCRIPTION*}"{+END} />{+START,IF,{EXPANDABLE}}</a>{+END}
{+END}
