[title="3"]{NAME@}[/title]

{+START,IF_PASSED,THUMBNAIL}[img float="right"]{$THUMBNAIL,{THUMBNAIL},200,,,,,,,1}[/img]{+END}{+START,IF_PASSED,DESCRIPTION}{+START,IF_NON_EMPTY,{DESCRIPTION}}{DESCRIPTION}

{+END}{+END}[url="{!VIEW#}"]{URL@}[/url]

