{TITLE}

{$TRIM,{RESULT}}

{+START,IF_NON_EMPTY,{MESSAGE}}
	{$PARAGRAPH,{MESSAGE}}
{+END}

{+START,IF_NON_EMPTY,{$TRIM,{CORRECTIONS_TO_SHOW}}}
	{+START,IF,{$NEQ,{TYPE},SURVEY}}
		<h2>{!_RESULTS}</h2>
	{+END}

	{$TRIM,{CORRECTIONS_TO_SHOW}}
{+END}

